### ISSUE TITLE
Containers 选择bridge联网方式报错，选择host没问题

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-app-dockerman#1]
Containers: start baidu...fail code:500 failed to create endpoint baidu on network bridge: adding interface vethf35946f to bridge dockerO failed: could not find bridge dockerO: route 
ip+net: no such network interface

**Comment by lisaac** [comment]
有这个提示，应该和插件无关，尝试使用命令行，是否有此错误？
