### ISSUE TITLE
dockerman是否和portainer有冲突？

### ISSUE THREAD

**Issue by ywgf88** [lisaac/luci-app-dockerman#10]
我使用lean的库编译op，并把docker-CE和dockerman，diskman也一同编译到固件。

1. 通过大雕之前提供的文档安装portainer: /etc/docker-web,成功安装portainer
2. 安装docker版aria2和jellyfin，都能很正常开启

but，当我重启路由器后，portainer和aria2，jellyfin就再也打不开了，通过后台和web都能看到他们都是running状态.
不知道是否dockerman和portainer是否不能同时运行导致冲突？

**Comment by lisaac** [comment]
没有冲突的，你再查一下，之前有反馈openwrt中的bridge模式有点问题 #6，不知道是这个原因？
