### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by binge8** [lisaac/luci-app-dockerman#100]
集成到大雕的openwrt不正常，系统日志有一条Devices cgroup isn't mounted
![微信截图_20210627000607](https://user-images.githubusercontent.com/53508344/123519058-a5a26f80-d6db-11eb-80f6-548fe9b04780.png)

**Comment by binge8** [comment]
好像是哪些依赖没选吧，也没汉化

**Comment by lisaac** [comment]
以来需要自己选择，汉化请PR

**Comment by binge8** [comment]
还有一个问题，左侧只有配置选项了，以前的概况，容器，镜像，网络，存储卷这些没有了，是我少选了哪些依赖吗
![微信截图_20210627091824](https://user-images.githubusercontent.com/53508344/123530032-c2b15f80-d728-11eb-8dc9-8df962046942.png)
![微信截图_20210627091859](https://user-images.githubusercontent.com/53508344/123530035-c644e680-d728-11eb-8bab-01ba49ed1b9a.png)

**Comment by lisaac** [comment]
> 还有一个问题，左侧只有配置选项了，以前的概况，容器，镜像，网络，存储卷这些没有了，是我少选了哪些依赖吗
> ![微信截图_20210627091824](https://user-images.githubusercontent.com/53508344/123530032-c2b15f80-d728-11eb-8dc9-8df962046942.png)
> ![微信截图_20210627091859](https://user-images.githubusercontent.com/53508344/123530035-c644e680-d728-11eb-8bab-01ba49ed1b9a.png)

在没有启动docker daemon的情况下，只会显示一个，等你docker daemon启动后，自动会显示出来的

**Comment by binge8** [comment]
> > 还有一个问题，左侧只有配置选项了，以前的概况，容器，镜像，网络，存储卷这些没有了，是我少选了哪些依赖吗
> > ![微信截图_20210627091824](https://user-images.githubusercontent.com/53508344/123530032-c2b15f80-d728-11eb-8dc9-8df962046942.png)
> > ![微信截图_20210627091859](https://user-images.githubusercontent.com/53508344/123530035-c644e680-d728-11eb-8bab-01ba49ed1b9a.png)
> 
> 在没有启动docker daemon的情况下，只会显示一个，等你docker daemon启动后，自动会显示出来的

我等了十几分钟也没启动起来，系统日志里有一条Devices cgroup isn't mounted，这是什么原因
