### ISSUE TITLE
dockerman设置目录好像和逻辑不一致

### ISSUE THREAD

**Issue by doumeki** [lisaac/luci-app-dockerman#101]
字段是data_root:
![image](https://user-images.githubusercontent.com/10527841/123545385-4bacb300-d78a-11eb-9676-af363713aaaf.png)
而UCI里好像期望的是 daemon_data_root
uci set dockerd.dockerman.daemon_data_root=`uci get dockerd.globals.data_root 2&> /dev/null || echo ''`
uci set dockerd.dockerman.daemon_log_level=`uci get dockerd.globals.log_level 2&> /dev/null || echo 'warn'`

**Comment by lisaac** [comment]
期待你的pr

**Comment by doumeki** [comment]
主要是连GIT都玩不转的老年人。如果我说错了就关了吧。我也是猜的。:(

**Comment by lisaac** [comment]
ok，最新pr把变量名改了。。回头改一致

**Comment by blusewang** [comment]
这个头回过来了么？
我也不知道这里该怎么配

**Comment by lisaac** [comment]
> 这个头回过来了么？ 我也不知道这里该怎么配

https://github.com/lisaac/luci-app-dockerman/commit/eaf2d4a42a28d8678ee17bfd937f494b90ba2fdb

**Comment by blusewang** [comment]
嗯，清了一下缓存，可以了。真香！
感谢🙏 @lisaac 的无私付出！
