### ISSUE TITLE
dockerman最新版出现这个错误！

### ISSUE THREAD

**Issue by shidahuilang** [lisaac/luci-app-dockerman#104]
![image](https://user-images.githubusercontent.com/81285256/123635217-02be3280-d84e-11eb-8f1c-bebc8afe98c0.png)

第一次创建没有错误，但是如果容器选择重启的话，就会提示这个错误，一直启动不来！

**Comment by lisaac** [comment]
> ![image](https://user-images.githubusercontent.com/81285256/123635217-02be3280-d84e-11eb-8f1c-bebc8afe98c0.png)
> 
> 
> 
> 第一次创建没有错误，但是如果容器选择重启的话，就会提示这个错误，一直启动不来！

使用命令行创建有错误吗

**Comment by 279437541** [comment]
使用命令行也可以创建，但是 不能在dockerman里面选择重启容器，容器容器后 在打开就这样错误。期间也没有重启过网络，但是如果路由器重启以后容器就可以正常开启了，dockerman里面选择重启容器就又回到了这样的错误！

**Comment by lisaac** [comment]
> 使用命令行也可以创建，但是 不能在dockerman里面选择重启容器，容器容器后 在打开就这样错误。期间也没有重启过网络，但是如果路由器重启以后容器就可以正常开启了，dockerman里面选择重启容器就又回到了这样的错误！

命令行重启呢？

**Comment by 279437541** [comment]
![image](https://user-images.githubusercontent.com/78850005/123738382-48730d80-d8d7-11eb-8a85-3575c7d17a35.png)
测试了命令行重启  暂时没发现问题 都是好好的

**Comment by lisaac** [comment]
> ![image](https://user-images.githubusercontent.com/78850005/123738382-48730d80-d8d7-11eb-8a85-3575c7d17a35.png)
> 测试了命令行重启 暂时没发现问题 都是好好的

现在这个阶段，用dockerman重启/启动，还是会报错吗？

**Comment by 279437541** [comment]
测试了现在这个阶段重启没有报错！很纳闷！

**Comment by 279437541** [comment]
我看看是不是我防火墙的问题！，麻烦大佬了

**Comment by lisaac** [comment]
> 我看看是不是我防火墙的问题！，麻烦大佬了

嗯，如果再次出现这种情况，请尝试下用命令行操作是否是同样的问题。
另外，我严重怀疑你应该是重启了网络才会出现这种情况
