### ISSUE TITLE
初始化配置不生效

### ISSUE THREAD

**Issue by doumeki** [lisaac/luci-app-dockerman#105]
经虚拟机测试， 在编译后第一次启动 uci-defaults/luci-app-dockerman：
ls /etc/rc.d/*dockerd >> /root/p.txt && uci set dockerd.dockerman.daemon_ea="true" || uci set dockerd.dockerman.daemon_ea="false"
uci set dockerd.dockerman.daemon_data_root=`uci get dockerd.globals.data_root 2&> /dev/null || echo ''`
uci set dockerd.dockerman.daemon_log_level=`uci get dockerd.globals.log_level 2&> /dev/null || echo 'warn'`
uci set dockerd.dockerman.daemon_bip=`uci get dockerd.globals.bip 2&> /dev/null || echo ''`

以上几个dockerman uci字段在刚开机时是不生效的。 通过打印/etc/config/dockerd找不到这几个配置， 猜测需要先创建dockerman的uci.

**Comment by lisaac** [comment]
期待pr

**Comment by lisaac** [comment]
已修复 https://github.com/lisaac/luci-app-dockerman/commit/1ddcbb4b977dbb0c9c25af953cb73fbdafe3b2e1
