### ISSUE TITLE
官方源码，内核5.4，编译出来容器页面500 内部服务器错误

### ISSUE THREAD

**Issue by CJLUGaoXinyu** [lisaac/luci-app-dockerman#106]
报错内容如下，求问如何解决

对不起，服务器遇到未知错误。

/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/simpleform'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:74: Failed to load template 'dockerman/containers_running_stats'.
Error while parsing template '/usr/lib/lua/luci/view/dockerman/containers_running_stats.htm':
No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:74: in function '__init__'
	/usr/lib/lua/luci/util.lua:65: in function 'Template'
	/usr/lib/lua/luci/template.lua:27: in function 'render'
	/usr/lib/lua/luci/cbi.lua:282: in function 'render'
	/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
	[string "/usr/lib/lua/luci/view/cbi/simpleform.htm"]:16: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:742: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:1511: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1025: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function 

查看目录后发现/usr/lib/lua/luci/view/dockerman/containers_running_stats.htm不存在，只存在/usr/lib/lua/luci/view/dockerman/container_stats.htm

**Comment by lisaac** [comment]
请问使用的是本仓库的代码吗？
