### ISSUE TITLE
运行一段时间后，只剩下概览菜单

### ISSUE THREAD

**Issue by hubumulity** [lisaac/luci-app-dockerman#107]
<img width="1191" alt="截屏2021-07-01 下午6 49 38" src="https://user-images.githubusercontent.com/55643426/124112664-19a69400-da9d-11eb-858b-317326fe76b3.png">

**Comment by lisaac** [comment]
1. 请确保 docker daemon 正常运行
2. 确保 dockerman 正确配置（socket path）
