### ISSUE TITLE
问一下CPU限制的问题

### ISSUE THREAD

**Issue by yuban10703** [lisaac/luci-app-dockerman#11]
![image](https://user-images.githubusercontent.com/39484884/74534090-f6de1300-4f6d-11ea-996c-31fb55f3bb0e.png)
![image](https://user-images.githubusercontent.com/39484884/74534130-0bbaa680-4f6e-11ea-8b28-5bb1682cb121.png)
cpu限制怎么关掉
emmm

**Comment by yuban10703** [comment]
填0.000提交后就直接返回信息界面了
![image](https://user-images.githubusercontent.com/39484884/74534236-41f82600-4f6e-11ea-9270-62aa0cb62d6c.png)

**Comment by lisaac** [comment]
0 是默认值，表示无限制
目前 docker 是无法改回 0 的
想要无限制直接改为上限就可以

**Comment by yuban10703** [comment]
好的,明白了

**Comment by lisaac** [comment]
另外，修改后应该是停留在编辑页面，不排除你修改菜单后导致返回问题

**Comment by yuban10703** [comment]
emm
