### ISSUE TITLE
一个或多个必选项值为空！

### ISSUE THREAD

**Issue by jarod360** [lisaac/luci-app-dockerman#110]
配置修改后，无法保存提示一个或多个必选项值为空！
![Screenshot_20210703_124430_alook browser](https://user-images.githubusercontent.com/32123167/124343226-88e6ca00-dbfc-11eb-87fd-b78a7ba8001c.jpg)

**Comment by hue715** [comment]
看看dockerman标签下是否有没设置的

**Comment by jarod360** [comment]
看了所有选项都有配置，而且容器也在运行！就是无法保存！除非把远程那个打勾，填上远程地址和端口能保存，但是本地的就出问题了

**Comment by jarod360** [comment]
![Screenshot_20210704_210604_alook browser](https://user-images.githubusercontent.com/32123167/124386161-abb3d400-dd0b-11eb-9ab5-5d1ca2bf0c39.jpg)
![Screenshot_20210704_210531_alook browser](https://user-images.githubusercontent.com/32123167/124386163-af475b00-dd0b-11eb-8341-2737971ecc5d.jpg)

**Comment by jarod360** [comment]
![Screenshot_20210704_210849_alook browser](https://user-images.githubusercontent.com/32123167/124386234-136a1f00-dd0c-11eb-8b4c-3b1ea79d4bfe.jpg)
![Screenshot_20210704_210845_alook browser](https://user-images.githubusercontent.com/32123167/124386237-15cc7900-dd0c-11eb-814c-ea47582a3e1d.jpg)
![Screenshot_20210704_210829_alook browser](https://user-images.githubusercontent.com/32123167/124386239-16fda600-dd0c-11eb-8e17-320008355547.jpg)

**Comment by hue715** [comment]
> 看了所有选项都有配置，而且容器也在运行！就是无法保存！除非把远程那个打勾，填上远程地址和端口能保存，但是本地的就出问题了

默认socket path是空值，需要填写，你看到的只是提示。

**Comment by jarod360** [comment]
![Uploading Screenshot_20210704_220434_alook.browser.jpg…]()

**Comment by jarod360** [comment]
> > 看了所有选项都有配置，而且容器也在运行！就是无法保存！除非把远程那个打勾，填上远程地址和端口能保存，但是本地的就出问题了
> 
> 默认socket path是空值，需要填写，你看到的只是提示。

不是空的

**Comment by jarod360** [comment]
![Screenshot_20210704_220434_alook browser](https://user-images.githubusercontent.com/32123167/124388124-fdf8f300-dd13-11eb-91f9-08d05f9dc1ba.jpg)

**Comment by jarod360** [comment]
另外网页服务没有用默认的uhttpd用的nginx 不知道跟这个有关系没

**Comment by hue715** [comment]
> 另外网页服务没有用默认的uhttpd用的nginx 不知道跟这个有关系没

没用最新的源码编译吧？最新的源码翻译都修复了，uci的执行也修复了

**Comment by jarod360** [comment]
是最新的源码呀，都是在线拉取这里的源码编译的，昨天编译的

**Comment by jarod360** [comment]
刚重新拉取编译，卸载之前安装还是一样，确认了就是这里的源码，没问题的！会不会跟uci设置里的uhttpd一些相关，默认的uhttpd已经改为nginx，固件里没有uhttpd

**Comment by lisaac** [comment]
> 刚重新拉取编译，卸载之前安装还是一样，确认了就是这里的源码，没问题的！会不会跟uci设置里的uhttpd一些相关，默认的uhttpd已经改为nginx，固件里没有uhttpd

请重新拉取并测试
