### ISSUE TITLE
无法创建容器

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [lisaac/luci-app-dockerman#111]
相关提示：
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/docker/newcontainer/opt/adg/opt/adguardhome/opt/adg/opt/adguardhome'.
The called action terminated with an exception:
...sr/lib/lua/luci/model/cbi/dockerman/newcontainer.lua:822: attempt to index upvalue 'create_body' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

创建命令行
docker run --name adguardhome \
        -v /opt/adg/work:/opt/adguardhome/work \
        -v /opt/adg/conf:/opt/adguardhome/conf \
        --restart always \
        --net host \
        -d adguard/adguardhome:arm64-latest

**Comment by lisaac** [comment]
> 相关提示：
> /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/docker/newcontainer/opt/adg/opt/adguardhome/opt/adg/opt/adguardhome'.
> The called action terminated with an exception:
> ...sr/lib/lua/luci/model/cbi/dockerman/newcontainer.lua:822: attempt to index upvalue 'create_body' (a nil value)
> stack traceback:
> [C]: in function 'assert'
> /usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
> /usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
> 
> 创建命令行
> docker run --name adguardhome
> -v /opt/adg/work:/opt/adguardhome/work
> -v /opt/adg/conf:/opt/adguardhome/conf
> --restart always
> --net host
> -d adguard/adguardhome:arm64-latest

本地测试无问题
麻烦给出 openwrt 版本、luci 版本、dockerman 版本

**Comment by ShoukakuChuuCC** [comment]
OpenWrt R21.7.1.100 / LuCI Master (git-21.188.53404-317d4ad)

Docker 版本 | 20.10.7
Api 版本 | 1.41

**Comment by lisaac** [comment]
> OpenWrt R21.7.1.100 / LuCI Master (git-21.188.53404-317d4ad)
> 
> Docker 版本 | 20.10.7
> Api 版本 | 1.41

dockerman 版本

**Comment by ShoukakuChuuCC** [comment]
luci-app-dockerman | v0.5.21-1

ARM平台，设备树莓派4B，最新自编译固件和最新第三方固件的dockerman均无法创建容器
luci-app-docker使用portainer面板创建正常

**Comment by lisaac** [comment]
> luci-app-dockerman | v0.5.21-1
> 
> ARM平台，设备树莓派4B，最新自编译固件和最新第三方固件的dockerman均无法创建容器
> luci-app-docker使用portainer面板创建正常

使用的是本仓库的源吗

**Comment by ShoukakuChuuCC** [comment]
是的

**Comment by ShoukakuChuuCC** [comment]
![截图20210710163239](https://user-images.githubusercontent.com/38343280/125157286-adaee480-e19c-11eb-9ec7-ec4a727df0ec.png)

**Comment by ShoukakuChuuCC** [comment]
![image](https://user-images.githubusercontent.com/38343280/125157300-c919ef80-e19c-11eb-852e-f7e9c5303388.png)

**Comment by ShoukakuChuuCC** [comment]
feeds.conf.default添加了src-git dockerman https://github.com/lisaac/luci-app-dockerman

**Comment by garypang13** [comment]
同样的问题.

**Comment by lisaac** [comment]
已修复，最近动的比较多，麻烦各位大佬帮忙多测试
