### ISSUE TITLE
最新dockerman编译好固件 vmware里面测试bridge可正常联网 刷进软路由无法联网 host没问题...

### ISSUE THREAD

**Issue by darktitty** [lisaac/luci-app-dockerman#112]
RT
软路由中bridge无法正常联网 vmware测试bridge没问题 什么情况...

**Comment by lisaac** [comment]
> RT
> 软路由中bridge无法正常联网 vmware测试bridge没问题 什么情况...

请先确认是docker(daemon)问题还是dockerman的问题

**Comment by darktitty** [comment]
> > RT
> > 软路由中bridge无法正常联网 vmware测试bridge没问题 什么情况...
> 
> 请先确认是docker(daemon)问题还是dockerman的问题

应该是docker自身问题吧 本身luci-app-docker也是这个问题(vmware和软路由都无法联网) 很奇怪dockerman为什么vmware可以软路由不可以啊... 请问大佬有解决方案吗?

**Comment by darktitty** [comment]
单插LAN口测试没问题 接上WAN口做主路由 bridge就无法联网...

**Comment by lisaac** [comment]
> 单插LAN口测试没问题 接上WAN口做主路由 bridge就无法联网...

检查 iptables 相关选项吧

**Comment by blacktitty-y** [comment]
> > 单插LAN口测试没问题 接上WAN口做主路由 bridge就无法联网...
> 
> 检查 iptables 相关选项吧

小白一枚 不会设置.... 换了两个软路由都不行... 是否可以发img给大佬测试下看看? 用的lean源码编译的

**Comment by lisaac** [comment]
> 小白一枚 不会设置.... 换了两个软路由都不行... 是否可以发img给大佬测试下看看? 用的lean源码编译的

发邮箱吧，有空看

**Comment by darktitty** [comment]
> > 小白一枚 不会设置.... 换了两个软路由都不行... 是否可以发img给大佬测试下看看? 用的lean源码编译的
> 
> 发邮箱吧，有空看

固件发你了 大佬~

**Comment by EnnawYang** [comment]
使用官方的21.02-rc3也是有这个问题，摸不着头脑

**Comment by edison0354** [comment]
应该是dockerd的问题。手动重启下iptables就能连上了，莫名其妙的bug，好久了……

**Comment by flyhong666** [comment]
我也是用bridge  弄的qbt 没法下载。改用host 就可以。。。

**Comment by lisaac** [comment]
#126
