### ISSUE TITLE
配置页面显示的不完整是什么原因造成的呢

### ISSUE THREAD

**Issue by ly88321** [lisaac/luci-app-dockerman#114]
**问题描述**
没有Docker Daemon settings
![image](https://user-images.githubusercontent.com/43890984/128971925-72c23f27-8a6b-4c45-9b07-cb6c24d273d0.png)

**Comment by lisaac** [comment]
请给出版本
因为没有检测到dockerd

**Comment by ly88321** [comment]
**版本信息:**
 - openwrt 版本：OpenWrt R21.8.6 /
 - luci 版本：LuCI Master (git-21.211.30217-03784c3)
 - docker daemon 版本：
dockerd | 20.10.7-1
 - dockerman 版本：
v0.5.23-2-1

**Comment by ly88321** [comment]
> 请给出版本
> 因为没有检测到dockerd

版本信息:

openwrt 版本：OpenWrt R21.8.6 /
luci 版本：LuCI Master (git-21.211.30217-03784c3)
docker daemon 版本：
dockerd | 20.10.7-1
dockerman 版本：
v0.5.23-2-1

**Comment by lisaac** [comment]
应该不会出现这种情况，其他正常吗

**Comment by ly88321** [comment]
编译的时候取消dockerce后正常了，已解决
关闭
