### ISSUE TITLE
请问一下这个docker 接口需要设置什么内容吗？

### ISSUE THREAD

**Issue by flyhong666** [lisaac/luci-app-dockerman#115]
![2021-08-14_204743](https://user-images.githubusercontent.com/76857714/129446814-4e0bbdee-825d-4dfb-b95c-da796904bbda.png)

**Comment by lisaac** [comment]
不需要设置，这个接口作用不大

**Comment by flyhong666** [comment]
但是 容器采用 bridge 模式都上不了网啊。直接将接口里面的这个删除有没有影响？

**Comment by lisaac** [comment]
这个接口是dockerd自动创建的，可以删除
