### ISSUE TITLE
无法启动docker daemon

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [lisaac/luci-app-dockerman#118]
**问题描述**
Please input the SOCKET PATH of docker daemon!
![image](https://user-images.githubusercontent.com/38343280/130720878-71b1deab-a696-48f9-ae17-7eb046b97593.png)

使用 dockerman 时遇到的问题
无法启动docker daemon，5.10.60内核

**版本信息:**
 - openwrt 版本：ImmortalWrt 18.06-SNAPSHOT r10715-6e40f735f 
 - luci 版本：LuCI openwrt-18.06-k5.4 branch (git-21.234.64951-9970507)
 - docker daemon 版本：没找到
 - dockerman 版本：v0.5.21-1

**Comment by ShoukakuChuuCC** [comment]
![image](https://user-images.githubusercontent.com/38343280/130721214-8af70459-bbb1-402b-9caa-2313ca9a2629.png)
![image](https://user-images.githubusercontent.com/38343280/130721229-d1710f91-a69c-41d9-b172-4cd84d18464f.png)
![image](https://user-images.githubusercontent.com/38343280/130721238-5cba40cf-a780-4b4e-aa66-3c78bf4860d2.png)

**Comment by ShoukakuChuuCC** [comment]
lean版openwrt正常，ImmortalWrt我没在feed.conf.default加入src-git dockerman https://github.com/lisaac/luci-app-dockerman，使用的是项目自带的dockerman

**Comment by lllrrr** [comment]
请问这个问题是怎么解决的，我也遇到这个问题了,谢谢

**Comment by ShoukakuChuuCC** [comment]
> 请问这个问题是怎么解决的，我也遇到这个问题了,谢谢

没解决，我换成luci-app-docker，用portainer面板，要不然换lean的openwrt

**Comment by lllrrr** [comment]
因为一个组件没有被选上+cgroupfs-mount  这个要手动选上

**Comment by ShoukakuChuuCC** [comment]
> 因为一个组件没有被选上+cgroupfs-mount 这个要手动选上

选上了的 还是不行
