### ISSUE TITLE
最新版本编译的，QBT 都没法正常工作啊。其他人情况怎样？

### ISSUE THREAD

**Issue by flyhong666** [lisaac/luci-app-dockerman#122]
用的是lead 代码编译的，用bridge或者host 模式都没法正常进行下载了。其他人怎样啊。

**Comment by acooler15** [comment]
用的openwrt 21.02，刚试了下好像正常
![image](https://user-images.githubusercontent.com/19186382/132124833-c8188b19-e1a4-45b4-a472-732eaf3055eb.png)

这玩意儿一直搞不懂需要设置啥，除了webUI外，其他的都是默认设置。。。

**Comment by flyhong666** [comment]
> 用的openwrt 21.02，刚试了下好像正常
> ![image](https://user-images.githubusercontent.com/19186382/132124833-c8188b19-e1a4-45b4-a472-732eaf3055eb.png)
> 
> 这玩意儿一直搞不懂需要设置啥，除了webUI外，其他的都是默认设置。。。

你这是在dockerman 运行的？docker pull johngong/qbittorrent:qee-latest 你拉取这个容器试一下。
https://hub.docker.com/r/johngong/qbittorrent  按这里配置。

**Comment by acooler15** [comment]
![image](https://user-images.githubusercontent.com/19186382/132127011-2c656eab-87e3-4e09-a4fa-d8c4a0405f56.png)
可以下载，感觉有点儿慢。。。

**Comment by acooler15** [comment]
都是用的Bridge

**Comment by flyhong666** [comment]
> 都是用的Bridge

我的host 或者bridge 都不行。不知道问题在哪。你是自己拉代码编译的么？

**Comment by acooler15** [comment]
> > 都是用的Bridge
> 
> 我的host 或者bridge 都不行。不知道问题在哪。你是自己拉代码编译的么？

是的，我用的树莓派，之前用lean的lede，但是总是死机，也找不到相关日志，后来就用openwrt官方的openwrt-21.04分支编译了。

你找个其它的镜像，运行后，进容器试试网络行不行。或者先把dockerman停掉试试，感觉跟dockerman的关系不太大。。。

**Comment by flyhong666** [comment]
> > > 都是用的Bridge
> > 
> > 
> > 我的host 或者bridge 都不行。不知道问题在哪。你是自己拉代码编译的么？
> 
> 是的，我用的树莓派，之前用lean的lede，但是总是死机，也找不到相关日志，后来就用openwrt官方的openwrt-21.04分支编译了。
> 
> 你找个其它的镜像，运行后，进容器试试网络行不行。或者先把dockerman停掉试试，感觉跟dockerman的关系不太大。。。

应该是这个的问题吧，我用aria2 那些也不行哦。

**Comment by acooler15** [comment]
> > > > 都是用的Bridge
> > > 
> > > 
> > > 我的host 或者bridge 都不行。不知道问题在哪。你是自己拉代码编译的么？
> > 
> > 
> > 是的，我用的树莓派，之前用lean的lede，但是总是死机，也找不到相关日志，后来就用openwrt官方的openwrt-21.04分支编译了。
> > 你找个其它的镜像，运行后，进容器试试网络行不行。或者先把dockerman停掉试试，感觉跟dockerman的关系不太大。。。
> 
> 应该是这个的问题吧，我用aria2 那些也不行哦。

dockerman与网络相关的就是几条iptables规则，而且都是关于访问容器的，应该没啥影响。可以先停掉dockerman（`/etc/init.d/dockerman stop`或者在luci页面中系统-启动项里停止掉dockerman）试试。

**Comment by acooler15** [comment]
对了，可以试着执行下这些命令：
```
/etc/init.d/dockerd stop;
/etc/init.d/dockerd ucidel;
/etc/init.d/dockerd uciadd;
/etc/init.d/dockerd start;
```
