### ISSUE TITLE
Docker安装在openWrt中（无论是否开启）会导致xray的Fullcone无效。

### ISSUE THREAD

**Issue by 1klakla1** [lisaac/luci-app-dockerman#125]
**问题描述**

Docker安装在openWrt中（无论是否开启）会导致xray的Fullcone无效。

-----------------------------------------------------------
相同案例传送门：
https://github.com/xiaorouji/openwrt-passwall/issues/1438
https://github.com/xiaorouji/openwrt-passwall/issues/1320

**Comment by lisaac** [comment]
应该去 openwrt 官方反馈这个问题吧

**Comment by 1klakla1** [comment]
英语水平不行，今天用中文反馈了一个，人家让我说英文。
囧

**Comment by lisaac** [comment]
> 英语水平不行，今天用中文反馈了一个，人家让我说英文。
> 囧

大概率不会修，官方本来就不知fullcone，再加上目前也不是100%确定与dockerd有关，有能力自己debug吧
