### ISSUE TITLE
无法连接到docker守护进程（docker daemon）

### ISSUE THREAD

**Issue by jack987-cloud** [lisaac/luci-app-dockerman#127]
**问题描述**

编译的官方源v21.02.0，原本官源带的有luci-app-dockerman，版本是v0.5.13，编译后不能运行。再次编译添加了v0.5.23-2版本的dockerman，改名为luci-app-dockerman2（编译时勾选，区别于自带源），编译成功后显示：无法连接到docker守护进程（docker daemon），卸载重新安装v0.2.23-2版本可以正常使用
![截屏2021-09-19 下午6 48 33](https://user-images.githubusercontent.com/60478985/133925552-d4ab4a76-113d-4533-8f13-e2c4dfe8583a.png)
![截屏2021-09-19 下午6 49 04](https://user-images.githubusercontent.com/60478985/133925553-62794666-7216-4e14-bc5b-8aaccd957e15.png)

。

**Comment by jack987-cloud** [comment]
怎么样设置才能编译完成就可以正常使用？

**Comment by jack987-cloud** [comment]
x86-64

**Comment by lisaac** [comment]
正常情况下不需要任何设置
若 dockerd 正常的情况下，最多就只需要启动 dockerd 就可以
两个版本的dockerman无法共存，编译是只能选其一。

**Comment by jack987-cloud** [comment]
就是v21.02.0不能用，才使用的v0.2.23-2。编译好后都不能用，显示：无法连接到docker守护进程（docker daemon）。卸载重新安装才能用。卸载重新安装的版本和编译的版本一样，编译哪里出问题了？有什么特别的设置吗？

**Comment by jack987-cloud** [comment]
官方自带的luci-app-dockerman没勾选，编译的时候只勾选luci-app-dockerman2

**Comment by lisaac** [comment]
> 什么

不能启动dockerd？

**Comment by jack987-cloud** [comment]
![133925552-d4ab4a76-113d-4533-8f13-e2c4dfe8583a](https://user-images.githubusercontent.com/60478985/133929700-cb838a74-90e4-43f3-b8b7-acfb9beac2b9.png)
就是这个界面，怎样查看不能启动的代码？

**Comment by lisaac** [comment]
> ![133925552-d4ab4a76-113d-4533-8f13-e2c4dfe8583a](https://user-images.githubusercontent.com/60478985/133929700-cb838a74-90e4-43f3-b8b7-acfb9beac2b9.png)
> 就是这个界面，怎样查看不能启动的代码？

左上角有按键，或者可以在命令行直接执行`dockerd`

**Comment by ASC8384** [comment]
> > ![133925552-d4ab4a76-113d-4533-8f13-e2c4dfe8583a](https://user-images.githubusercontent.com/60478985/133929700-cb838a74-90e4-43f3-b8b7-acfb9beac2b9.png)
> > 就是这个界面，怎样查看不能启动的代码？
> 
> 左上角有按键，或者可以在命令行直接执行`dockerd`

版本 Powered by LuCI openwrt-23.05 branch (git-2a9c3a3), 插件版本 v0.5.26，点启动或者重新启动都没有用，但是手动在命令行直接执行`dockerd`就可以正常运行

**Comment by LanYunDev** [comment]
luci-app-dockerman v0.5.26-1 无法通过网页启动docker守护进程.命令dockerd可以启动,

**Comment by LanYunDev** [comment]
> > > ![133925552-d4ab4a76-113d-4533-8f13-e2c4dfe8583a](https://user-images.githubusercontent.com/60478985/133929700-cb838a74-90e4-43f3-b8b7-acfb9beac2b9.png)
> > > 就是这个界面，怎样查看不能启动的代码？
> > 
> > 
> > 左上角有按键，或者可以在命令行直接执行`dockerd`
> 
> 版本 Powered by LuCI openwrt-23.05 branch (git-2a9c3a3), 插件版本 v0.5.26，点启动或者重新启动都没有用，但是手动在命令行直接执行`dockerd`就可以正常运行

一样问题

**Comment by nagilezhou** [comment]
我也遇到这个问题了，点启动或者重新启动都没有用，但是手动在命令行直接执行dockerd就可以正常运行
