### ISSUE TITLE
luci-application中找不到dockerman

### ISSUE THREAD

**Issue by biggbuddy** [lisaac/luci-app-dockerman#129]
**问题描述**

在今天拉到的最新的lede源码, 并同时拉了最新的dockerman代码放在 lede/packages/lean目录下, 但在make menuconfig的时候, luci --> applications里面找不到DockerMan.

**使用命令行**
n/a

**版本信息:**
 - openwrt 版本：2021-10-18的最新版
 - luci 版本：2021-10-18的最新版
 - docker daemon 版本：2021-10-18的最新版
 - dockerman 版本：2021-10-18的最新版

**Comment by lisaac** [comment]
修改 `feeds.conf.default`，加入本仓库地址

**Comment by biggbuddy** [comment]
删除原来的.config文件就可以了, 不好意思, 不是很熟悉.

感谢回复
