### ISSUE TITLE
如果镜像稍大会 Bad Gateway

### ISSUE THREAD

**Issue by lloyd18** [lisaac/luci-app-dockerman#13]
小的没问题 如aria2
大的有问题 如netdata

netdata参数如下

docker run -d --name=netdata \
  -p 19999:19999 \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata

![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/74603738-ad1e3580-50f1-11ea-8fab-bb136f24ce10.jpg)

**Comment by lloyd18** [comment]
在终端里运行没问题

**Comment by lisaac** [comment]
两个方案
1.加快网速，使得拉取镜像更快(60以内)
2.改大uhttpd等待cgi时间，比如600秒

**Comment by lloyd18** [comment]
按你说的，已经正常，感谢大佬的帮助

**Comment by tty228** [comment]
# 更改 uhttpd 脚本超时时间，避免如 docker 拉取失败
uci set uhttpd.uhttpd.script_timeout='1800'
uci commit uhttpd
/etc/init.d/uhttpd restart
