### ISSUE TITLE
关于容器的Block IO weight问题

### ISSUE THREAD

**Issue by acooler15** [lisaac/luci-app-dockerman#131]
**问题描述**

看到openwrt论坛，和github上有人在讨论，在config-5.4和config-5.10的内核配置中`CONFIG_BLK_CGROUP_IOCOST `默认是不使用的，是否有必要在Makefile中启用这个选项，或者移除`blkioweight`这个Option，也或许可以使用一些方式检测`BLK_CGROUP_IOCOST`是否启用来`blkioweight`这个Option？

openwrt/luci/issues/5327
https://forum.openwrt.org/t/snapshot-cgroup-options-break-docker/102531/4

**版本信息:**
 - openwrt 版本：
 - luci 版本：
 - docker daemon 版本：
 - dockerman 版本：

**Comment by lisaac** [comment]
我记得很早就修复了，只是没有同步到openwrt官方仓库

https://github.com/lisaac/luci-app-dockerman/commit/75813385deb83113e9874ccb538f91db10c81046#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc

**Comment by acooler15** [comment]
> 我记得很早就修复了，只是没有同步到openwrt官方仓库
> 
> [7581338#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc](https://github.com/lisaac/luci-app-dockerman/commit/75813385deb83113e9874ccb538f91db10c81046#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc)

![image](https://user-images.githubusercontent.com/19186382/140918015-5a81ee32-b753-4251-b424-28d121e25853.png)

如果给它赋值的话依然会出问题
![image](https://user-images.githubusercontent.com/19186382/140917655-7b0e1c7d-4a13-4e35-95e4-f76cdaec6366.png)


我试试能不能通过检测kernel配置`BLK_CGROUP_IOCOST`，判断能否隐藏该选项。。。

**Comment by lisaac** [comment]
> > 我记得很早就修复了，只是没有同步到openwrt官方仓库
> 
> > 
> 
> > [7581338#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc](https://github.com/lisaac/luci-app-dockerman/commit/75813385deb83113e9874ccb538f91db10c81046#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/19186382/140918015-5a81ee32-b753-4251-b424-28d121e25853.png)
> 
> 
> 
> 如果给它赋值的话依然会出问题
> 
> ![image](https://user-images.githubusercontent.com/19186382/140917655-7b0e1c7d-4a13-4e35-95e4-f76cdaec6366.png)
> 
> 
> 
> 
> 
> 我试试能不能通过检测kernel配置`BLK_CGROUP_IOCOST`，判断能否隐藏该选项。。。

原本这个问题是创建容器的时候给了一个默认的值才会导致所有容器都会有这个问题
隐藏还是算了，可能需要隐藏的内容就太多了，还多都是依赖内核模块的

**Comment by acooler15** [comment]
> > > 我记得很早就修复了，只是没有同步到openwrt官方仓库
> > 
> > 
> > > 
> > 
> > 
> > > [7581338#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc](https://github.com/lisaac/luci-app-dockerman/commit/75813385deb83113e9874ccb538f91db10c81046#diff-117047b2dc6450eae4622e1aadc0de43e3a5660b5be5e66b74ad122e15d08abc)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19186382/140918015-5a81ee32-b753-4251-b424-28d121e25853.png)
> > 如果给它赋值的话依然会出问题
> > ![image](https://user-images.githubusercontent.com/19186382/140917655-7b0e1c7d-4a13-4e35-95e4-f76cdaec6366.png)
> > 我试试能不能通过检测kernel配置`BLK_CGROUP_IOCOST`，判断能否隐藏该选项。。。
> 
> 原本这个问题是创建容器的时候给了一个默认的值才会导致所有容器都会有这个问题 隐藏还是算了，可能需要隐藏的内容就太多了，还多都是依赖内核模块的

好的。
