### ISSUE TITLE
docker 无法创建容器

### ISSUE THREAD

**Issue by sky2016cn** [lisaac/luci-app-dockerman#133]
**问题描述**

使用 dockerman 时遇到的问题
无法创建容器，系统日志提示：Sun Nov 21 10:01:48 2021 daemon.err dockerd[5895]: time="2021-11-21T02:01:48.784055285Z" level=error msg="Handler for POST /containers/create returned error: json: cannot unmarshal array into Go struct field HostConfig.HostConfig.LogConfig of type container.LogConfig"

**使用命令行**

**版本信息:**
 - openwrt 版本：最新编译 Lean 的 OpenWrt R21.11.11
 - luci 版本：LuCI Master (git-21.320.49600-21168d4)
 - docker daemon 版本：
 - dockerman 版本：20.10.10

**Comment by lisaac** [comment]
bug: 已经修复
