### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by sheno-Tyes** [lisaac/luci-app-dockerman#134]
docker: Error response from daemon: failed to create endpoint alist on network bridge: adding interface vetheb87cd3 to bridge docker0 failed: could not find bridge docker0: route ip+net: no such network interface.
需手动重启docker

**版本信息:**
 - openwrt 版本：R21.11.11
 - luci 版本：
 - docker daemon 版本：20.10.11-1
 - dockerman 版本：v0.5.25-1

**Comment by sheno-Tyes** [comment]
还是不行

**Comment by fuergaosi233** [comment]
同样的问题
