### ISSUE TITLE
OpenWrt 系统日志提示 docker 环路了

### ISSUE THREAD

**Issue by sky2016cn** [lisaac/luci-app-dockerman#136]
**OpenWrt 系统日志提示 docker 环路了**

**系统日志**
Fri Dec  3 13:20:45 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:45.779582614Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Fri Dec  3 13:20:46 2021 daemon.err modprobe: failed to find a module named aufs
Fri Dec  3 13:20:46 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:46.359454992Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Fri Dec  3 13:20:46 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:46.360398694Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
Fri Dec  3 13:20:46 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:46.817510848Z" level=warning msg="Your kernel does not support swap memory limit"
Fri Dec  3 13:20:46 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:46.817538754Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Fri Dec  3 13:20:46 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:46.817549812Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Fri Dec  3 13:20:46 2021 daemon.err dockerd[5028]: time="2021-12-03T05:20:46.872313444Z" level=warning msg="Failed to find ip6tables: exec: \"ip6tables\": executable file not found in $PATH"
Fri Dec  3 13:20:46 2021 kern.info kernel: [   20.470616] e1000e: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx

**版本信息:**
 - openwrt 版本：Lean 的 OpenWrt R21.11.11/ 5.4.162
 - luci 版本：LuCI Master (git-21.329.83689-00cb491)
 - docker	20.10.11-1
 - dockerd	20.10.11-1
 - luci-app-dockerman	v0.5.25-1
 - luci-i18n-dockerman-zh-cn	v0.5.25-1
 - luci-lib-docker	v0.3.4-1

**Comment by lisaac** [comment]
dockerd 相关，自行添加相应内核模块
