### ISSUE TITLE
创建容器出错

### ISSUE THREAD

**Issue by sheno-Tyes** [lisaac/luci-app-dockerman#137]
**问题描述**

/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute cbi dispatcher target for entry '/admin/docker/newcontainer/opt/alist'.
The called action terminated with an exception:
/usr/lib/lua/luci/docker.lua:119: attempt to index global 'options' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**版本信息:**
 - openwrt 版本：19.07-SNAPSHOT
 - luci 版本：17.01 Lienol 
 - docker daemon 版本：20.10.11
 - dockerman 版本：v0.5.25

**Comment by lisaac** [comment]
请给出 luci-lib-docker 版本

**Comment by sheno-Tyes** [comment]
看了下，luci-lib-docker 版本0.3.3，0.3.4 编译出来再试下。。。。
