### ISSUE TITLE
Docker容器在宽带账号重拨后无法联网

### ISSUE THREAD

**Issue by thisdk** [lisaac/luci-app-dockerman#139]
**问题描述**

使用 dockerman 时遇到的问题

Docker容器在宽带账号重拨后无法联网,重现方法比较简单,只需要在接口重启wan口即可.(假装重新拨号)

其实这个问题我不知道找谁,因为我也不确定是系统的问题还是插件的问题.

**使用命令行**
同样的操作使用命令行的结果

**版本信息:**
 - openwrt 版本：ImmortalWrt SNAPSHOT r21205-ff4cbb40f2
 - luci 版本：ImmortalWrt SNAPSHOT r21205-ff4cbb40f2
 - docker daemon 版本：20.10.11-1
 - dockerman 版本：v0.5.25

**Comment by lisaac** [comment]
用的是macvlan网络吧？
可能是ifup和docker不兼容导致的问题，与dockerman是无关的

**Comment by thisdk** [comment]
> 用的是macvlan网络吧？ 可能是ifup和docker不兼容导致的问题，与dockerman是无关的

我也不太清楚,今晚回去看看才知道.因为这个dockerman插件不是编译进去的,而是安装进去的,除了大佬你的luci-app-dockerman,其他的全是仓库的依赖.
