### ISSUE TITLE
Bug report:Images: pulling failed ... Code 500

### ISSUE THREAD

**Issue by lqdflying** [lisaac/luci-app-dockerman#14]
<img width="515" alt="docker" src="https://user-images.githubusercontent.com/30266323/74936254-c8a47b80-5424-11ea-976d-ae54c2cdec8c.png">

**Comment by lisaac** [comment]
请尝试命令行是否正常？
若不正常，docker版本是多少？

**Comment by lqdflying** [comment]
Docker版本 | 19.03.3
cli 正常

**Comment by lisaac** [comment]
在概览页面打开debug
用ui重新pull
tail -n 100 /tmp/.docker_debug

**Comment by lqdflying** [comment]
`  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r2027-9fedd2b
 -----------------------------------------------------
root@liuqd:~# tail -n 100 /tmp/.docker_debug
GET /_ping HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /_ping HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /_ping HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /networks HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /_ping HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /images/json HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /containers/json?all=true HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /_ping HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /images/json HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /containers/json?all=true HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


POST /images/create?fromImage= HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close
X-Registry-Auth: eyJzZXJ2ZXJhZGRyZXNzIjoiaW5kZXguZG9ja2VyLmlvIn0=


GET /_ping HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /images/json HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


GET /containers/json?all=true HTTP/1.1
Host: localhost
User-Agent: LuCI
Connection: close


root@liuqd:~# 
`

**Comment by lisaac** [comment]
不同版本的luci可能存在差异
明天修复

**Comment by lqdflying** [comment]
感谢大佬

**Comment by lisaac** [comment]
我看了下lean那边的源码，发现他把placeholder改成了hello-world:latest了
然后你这个主题placeholder和真实输入的内容是不是一样的样式
你是否没有输入镜像名称？直接点了pull?

**Comment by lqdflying** [comment]
是的哥,成功了,我以为默认给我填了hello-world:latest,直接点了测试.是我的问题,,不是bug,问题解决
