### ISSUE TITLE
dockerman网络规则疑问

### ISSUE THREAD

**Issue by qiuzi** [lisaac/luci-app-dockerman#141]
iptables_append DOCKER-MAN -m conntrack --ctstate NEW,INVALID -o docker0 -j DROP >/dev/null 2>&1

限制外网访问容器出于安全方面吗？ 我认为既然都是容器了就不必限制外部网络服务

**Comment by lisaac** [comment]
可以在dockerman中设置，那些容器端口可以被访问

**Comment by qiuzi** [comment]
这小细节原来如此，还有就是保存路径地址应用时程序不会restart吗？ 需要手动点击重启服务
