### ISSUE TITLE
docker 默认网络疑问，自建网络不走ssr+问题

### ISSUE THREAD

**Issue by Xunflash** [lisaac/luci-app-dockerman#143]
**问题描述**

A：问题一：使用dockerman创建两个容器，使用默认桥接（bridge）模式时，宿主机（OpenWrt）重启后会使两个容器分配的ip互换（默认网段是172.17.0.0/16 现假设容器A分配了172.17.0.2，容器B分配172.17.0.3，在宿主机重启后，会根据容器启动的顺序给容器分配ip，一些时候会让容器A分配到172.17.0.3，容器B分配到0.2
在这种情况下，两个容器的服务都会失效（容器A web服务访问提示ERR_HTTP_RESPONSE_CODE_FAILURE））

问题二：尝试不使用默认网络bridge，自建网络my_net，定义网段172.20.0.0/16，使用固定IP启动容器，在宿主机重启时并没有问题，但是这种方法容器不走宿主机ssr+代理（默认网桥绑定了docker0接口，在ssr+勾选即可，自己创建的并没有绑定接口）

期望的解决方案：容器在宿主机重启时正常启动并且走ssr+代理。

**使用命令行**
同样的操作使用命令行的结果
暂未测试，有需求再测试

**版本信息:**
 - openwrt 版本：ImmortalWrt 18.06-5.4-SNAPSHOT r11579-375f97f0e5 (2022-01-25) / LuCI openwrt-18.06-k5.4 branch (git-22.021.28427-2a43828)
 - docker daemon 版本：20.10.11-1
 - dockerman 版本：v0.5.25-1

**Comment by lisaac** [comment]
@Xunflash 
1.不知道你的服务是什么，对于bridge网络，不用过于在意容器的ip地址，一般使用bridge网络的容器是将端口映射出去的。在这个前提下，dockerman提供了网络的访问控制，允许来自wan的流量访问特定的端口（即容器暴露的端口）
如果你的2个容器需要互相通信，可以尝试使用--link，或者自建网络后用容器名来通信

2.我自己没使用ssr+，不了解情况，你可以尝试自己创建接口，希望有结果po出来

**Comment by Xunflash** [comment]
> @Xunflash 
> 1.不知道你的服务是什么，对于bridge网络，不用过于在意容器的ip地址，一般使用bridge网络的容器是将端口映射出去的。在这个前提下，dockerman提供了网络的访问控制，允许来自wan的流量访问特定的端口（即容器暴露的端口）
> 如果你的2个容器需要互相通信，可以尝试使用--link，或者自建网络后用容器名来通信
> 
> 2.我自己没使用ssr+，不了解情况，你可以尝试自己创建接口，希望有结果po出来

![Screenshot_2022-02-05-20-31-00-429_mark.via.jpg](https://user-images.githubusercontent.com/71567536/152642841-0adab802-92f7-478a-842e-32aca9f162b5.jpg)

其实问题1说复杂了，一句话概括就是：树莓派重启导致容器ip变乱并且容器服务无法访问。

为什么要强调ip是因为我测试按照重启前的ip顺序依次重启容器后，容器服务恢复正常了。我就粗略认为是ip变化导致服务异常。

这个问题也是关键，不能因为树莓派每天的定时重启导致每次我都要手动去dockerman里面重新启动。

因为这个问题1我才衍生出问题2，自建网络导致的无法访问代理。

自己创建接口我也在luci界面试过了，按照docker0接口一样重新创建了一个docker1并且在防火墙里面也设置了，但是好像没有什么用。命令行我没找到有相关教程。

关于日志，主要是这个问题涉及到重新启动，我也不清楚要怎么测试贴日志结果，只好文字描述

**Comment by acooler15** [comment]
容器在创建时可以指定IP，容器互相访问可以使用link
