### ISSUE TITLE
无法使用控制台

### ISSUE THREAD

**Issue by People-11** [lisaac/luci-app-dockerman#144]
**问题描述**

昨天对固件进行重新编译并更新，发现容器内的控制台功能无法使用
![image](https://user-images.githubusercontent.com/41558215/153454321-ca7e426d-164d-42c8-8c0c-6f6644595181.png)

**使用命令行**
没有问题

**版本信息:**
 - openwrt 版本：OpenWrt 21.02.1 r16325-88151b8303
 - luci 版本：LuCI openwrt-21.02 branch (git-22.036.36928-b620cca)
 - docker daemon 版本：20.10.11
 - dockerman 版本：最新

**Comment by mingxiaoyu** [comment]
同问

**Comment by lisaac** [comment]
#142 引入的bug，已修
