### ISSUE TITLE
设置中没有展示Docker Daemon设置栏

### ISSUE THREAD

**Issue by javanli** [lisaac/luci-app-dockerman#146]
**问题描述**

设置中没有展示Docker Daemon设置栏

docker运行正常

可能是什么原因呢？

**版本信息:**
 - openwrt 版本：R22.3.13（lean的版本）
 - luci 版本：git-22.068.45502-a50e601
 - docker daemon 版本：20.10.12-1
 - dockerman 版本：v0.5.25-1

**Comment by lisaac** [comment]
大概率 dockerd 配置文件相关内容缺失导致

**Comment by Acris** [comment]
最近的OpenWrt Snapshot版本确实不显示设置项了，只有一个最顶层的配置。

**Comment by davidtall** [comment]
same issue

**Comment by samlin39** [comment]
> **问题描述**
> 
> 设置中没有展示Docker Daemon设置栏
> 
> docker运行正常
> 
> 可能是什么原因呢？
> 
> **版本信息:**
> 
> * openwrt 版本：R22.3.13（lean的版本）
> * luci 版本：git-22.068.45502-a50e601
> * docker daemon 版本：20.10.12-1
> * dockerman 版本：v0.5.25-1

https://github.com/lisaac/luci-app-dockerman/issues/140#issuecomment-1493037277
