### ISSUE TITLE
无法连接到docker守护进程（docker daemon）

### ISSUE THREAD

**Issue by lfscqk67** [lisaac/luci-app-dockerman#147]
**问题描述**

无法连接到docker守护进程（docker daemon），请检查!!

**版本信息:**
 - openwrt 版本：5.4.179-flippy-69+o
 - luci 版本：LuCI Master (git-21.335.48743-5f363d9)

![image](https://user-images.githubusercontent.com/37235589/160823188-6dea5b9d-ea90-47ae-909f-806db48860a7.png)

**Comment by lisaac** [comment]
#127
