### ISSUE TITLE
关于显示的问题

### ISSUE THREAD

**Issue by yuban10703** [lisaac/luci-app-dockerman#15]
![image](https://user-images.githubusercontent.com/39484884/75023392-b41ebc80-54d2-11ea-9d54-e34c27a9f49e.png)
内存显示好像有点问题,我原来是4G内存显示是正常的,然后又加了条2G,然后就只显示2G了
docker镜像数量貌似把中间层镜像也算进去了
![image](https://user-images.githubusercontent.com/39484884/75023590-07910a80-54d3-11ea-95a7-5251a2db62df.png)
![image](https://user-images.githubusercontent.com/39484884/75023683-2bece700-54d3-11ea-96e1-1803776c1265.png)

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/75023812-66568400-54d3-11ea-87ab-c55e211374eb.png)

**Comment by lisaac** [comment]
- overview 页面中的数量的确把所有镜像都算进去了，下个版本会修正
 - 关于内存问题，运行 `docker info` 查看内存信息是否完整

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/75027010-d9162e00-54d8-11ea-8ed9-bcbcb7638694.png)
e'm'm'memmm

**Comment by lisaac** [comment]
这就奇怪了，没有找到原因，另外我自己16g内存都能正常显示
你再查一下

**Comment by yuban10703** [comment]
emmmmmm
我再把2G拔了试试

**Comment by yuban10703** [comment]
![@Q3 BH_B5TVOJQ4B$P_YP0L](https://user-images.githubusercontent.com/39484884/75028735-c8b38280-54db-11ea-9695-c2ed8acfa17c.png)
![P4R}2` HE@4WAJW}576Q@7N](https://user-images.githubusercontent.com/39484884/75028738-ca7d4600-54db-11ea-8436-3c26f638b00e.png)
4G又正常了
我试试只插2g....

**Comment by yuban10703** [comment]
2G貌似也正常emmmmm
![0JY())` DHLIU%Q X@0)Q2I](https://user-images.githubusercontent.com/39484884/75029922-fe596b00-54dd-11ea-9f76-4cffbe8d7930.png)
插回去又不正常了...玄学
![KU3FO7AE%813~WKY9I 0PKD](https://user-images.githubusercontent.com/39484884/75029978-1c26d000-54de-11ea-9061-9175329bb236.png)

**Comment by lisaac** [comment]
贴一下
```
docker info --format '{{json .}}'
```

**Comment by yuban10703** [comment]
root@OpenWrt:~# docker info --format '{{json .}}'
{"ID":"WRRY:AKZS:MUKF:YXL4:DLY5:GZVC:5YEP:K2LR:F63S:4M7R:QVPH:L45F","Containers":3,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":3,"Images":16,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"]],"SystemStatus":null,"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":true,"KernelMemoryTCP":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":20,"OomKillDisable":true,"NGoroutines":40,"SystemTime":"2020-02-21T11:22:49.00825181Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","NEventsListener":0,"KernelVersion":"4.19.101","OperatingSystem":"OpenWrt SNAPSHOT","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":4,"MemTotal":6083469312,"GenericResources":null,"DockerRootDir":"/opt/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"OpenWrt","Labels":[],"ExperimentalBuild":false,"ServerVersion":"19.03.3","ClusterStore":"","ClusterAdvertise":"","Runtimes":{"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"b34a5c8af56e510852c35414db4c1f4fa6172339","Expected":"b34a5c8af56e510852c35414db4c1f4fa6172339"},"RuncCommit":{"ID":"3e425f80a8c931f88e6d94a8c831b9d5aa481657","Expected":"3e425f80a8c931f88e6d94a8c831b9d5aa481657"},"InitCommit":{"ID":"","Expected":""},"SecurityOptions":null,"Warnings":null,"ClientInfo":{"Debug":false,"Plugins":[],"Warnings":null}}

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/75030773-cc490880-54df-11ea-8591-2ec29e174790.png)

**Comment by lisaac** [comment]
```
sed -i 's/tostring(byte_format(docker_info.body.MemTotal))/tostring(docker_info.body.MemTotal)/' /u
sr/lib/lua/luci/model/cbi/docker/overview.lua
rm -fr /tmp/luci-*
```
然后重新查看 overview

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/75031897-3f537e80-54e2-11ea-9a06-72217935c83e.png)
emmm

**Comment by lisaac** [comment]
这可能是个 bug，也又可能是 docker-ce 的bug
由于 lede 的 curl 翔一样，而且又只在你这种情况下出现。。暂时无法调试
可以尝试重新刷一个更高版本的 docker-ce 试一下

**Comment by yuban10703** [comment]
emmmmm
我试试

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/75035131-c2c49e00-54e9-11ea-92d7-960c4d46ebf2.png)
换了个高版本好像还是不行emmm

**Comment by lisaac** [comment]
```
docker run --rm -v /var/run/docker.sock:/docker.sock -u 0:0 curlimages/curl curl -v --unix-socket /docker.sock http://localhost/info
```

**Comment by yuban10703** [comment]
root@OpenWrt:~# docker run --rm -v /var/run/docker.sock:/docker.sock -u 0:0 curlimages/curl curl -v --unix-socket /docker.sock http://localhost/info
Unable to find image 'curlimages/curl:latest' locally

latest: Pulling from curlimages/curl
89d9c30c1d48: Pull complete 
2f525b42acd2: Pull complete 
Digest: sha256:99a8e9629b3ae26efb977e1a98f4786d6bd730c5ab4dea64632e297d7c3e7151
Status: Downloaded newer image for curlimages/curl:latest
*   Trying /docker.sock:0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> GET /info HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.40
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/19.03.6 (linux)
< Date: Fri, 21 Feb 2020 13:02:08 GMT
< Transfer-Encoding: chunked
< 
{ [2185 bytes data]
100  2173    0  2173    0     0   151k      0 --:--:-- -{"ID":"3VQ3:MBVH:ONEG:6OX3:M3IJ:QCX4:IZA7:QW6J:5GCD:WVQU:JVCU:53OU","Containers":4,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":4,"Images":17,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"]],"SystemStatus":null,"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":true,"KernelMemoryTCP":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":29,"OomKillDisable":true,"NGoroutines":56,"SystemTime":"2020-02-21T13:02:08.809910373Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","NEventsListener":0,"KernelVersion":"4.19.101","OperatingSystem":"OpenWrt SNAPSHOT","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":4,"MemTotal":6083469312,"GenericResources":null,"DockerRootDir":"/opt/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"OpenWrt","Labels":[],"ExperimentalBuild":false,"ServerVersion":"19.03.6","ClusterStore":"","ClusterAdvertise":"","Runtimes":{"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"b34a5c8af56e510852c35414db4c1f4fa6172339","Expected":"b34a5c8af56e510852c35414db4c1f4fa6172339"},"RuncCommit":{"ID":"3e425f80a8c931f88e6d94a8c831b9d5aa481657","Expected":"3e425f80a8c931f88e6d94a8c831b9d5aa481657"},"InitCommit":{"ID":"","Expected":""},"SecurityOptions":null,"Warnings":null}
-:--:-- --:--:--  163k
* Connection #0 to host localhost left intact
root@OpenWrt:~# 
root@OpenWrt:~# 
![image](https://user-images.githubusercontent.com/39484884/75036721-8135f200-54ed-11ea-948c-d0876e15d3cb.png)

**Comment by yuban10703** [comment]
` -----------------------------------------------------
root@OpenWrt:~# docker run --rm -v /var/run/docker.sock:/docker.sock -u 0:0 curlimages/curl curl -v --unix-socket /docker.sock http://localhost/info
Unable to find image 'curlimages/curl:latest' locally

latest: Pulling from curlimages/curl
89d9c30c1d48: Pull complete 
2f525b42acd2: Pull complete 
Digest: sha256:99a8e9629b3ae26efb977e1a98f4786d6bd730c5ab4dea64632e297d7c3e7151
Status: Downloaded newer image for curlimages/curl:latest
*   Trying /docker.sock:0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> GET /info HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.40
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/19.03.6 (linux)
< Date: Fri, 21 Feb 2020 13:02:08 GMT
< Transfer-Encoding: chunked
< 
{ [2185 bytes data]
100  2173    0  2173    0     0   151k      0 --:--:-- -{"ID":"3VQ3:MBVH:ONEG:6OX3:M3IJ:QCX4:IZA7:QW6J:5GCD:WVQU:JVCU:53OU","Containers":4,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":4,"Images":17,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"]],"SystemStatus":null,"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":true,"KernelMemoryTCP":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":29,"OomKillDisable":true,"NGoroutines":56,"SystemTime":"2020-02-21T13:02:08.809910373Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","NEventsListener":0,"KernelVersion":"4.19.101","OperatingSystem":"OpenWrt SNAPSHOT","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":4,"MemTotal":6083469312,"GenericResources":null,"DockerRootDir":"/opt/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"OpenWrt","Labels":[],"ExperimentalBuild":false,"ServerVersion":"19.03.6","ClusterStore":"","ClusterAdvertise":"","Runtimes":{"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"b34a5c8af56e510852c35414db4c1f4fa6172339","Expected":"b34a5c8af56e510852c35414db4c1f4fa6172339"},"RuncCommit":{"ID":"3e425f80a8c931f88e6d94a8c831b9d5aa481657","Expected":"3e425f80a8c931f88e6d94a8c831b9d5aa481657"},"InitCommit":{"ID":"","Expected":""},"SecurityOptions":null,"Warnings":null}
-:--:-- --:--:--  163k
* Connection #0 to host localhost left intact
`

**Comment by lisaac** [comment]
与 luci-lib-json 相关的上游 bug
使用 lean 版 luci 中 使用 luci-lib-json 时
会导致 json 转 table 时的数字的种种问题，具体表现
```
>print(json.decode('{"b":6083469312}')["b"])
1788502016
```

而在最新 19.07.1 版本 luci 中没有这个问题
```
> print(json.decode('{"b":6083469312}')["b"])
6083469312
```

之前使用过 luci-lib-jsonc，但是 lean 老版本的 josnc 有一个 bug 导致溢出https://github.com/openwrt/luci/issues/3293
@coolsnowwolf 那边还没修复，所以改为了 luci-lib-json 作为依赖

现在既然使用两个库都有一些 bug，下个版本直接使用 luci-lib-jsonc 作为依赖

**Comment by yuban10703** [comment]
emmm神奇:sweat_drops:

**Comment by adaaaaaa** [comment]
我的也是显示2G，实际有32G内存。。。
现在修好了吗？？我dockerman已经是最新了。。。

**Comment by lisaac** [comment]
好了，已经改 luci-lib-jsonc 作为依赖

目前18.06 19.07 版本 Luci 均正常

导致不正常是因为 lean 仓库中的 luci 没有修复https://github.com/openwrt/luci/issues/3293 这个 bug 所导致的
