### ISSUE TITLE
This is forgotten?

### ISSUE THREAD

**Issue by castillofrancodamian** [lisaac/luci-app-dockerman#150]
I see that the latest updates are not in OpenWrt.

**Comment by haze1986** [comment]
Yes I guess it has been abandoned

**Comment by castillofrancodamian** [comment]
I ask because in OpenWrt there is an even older version that has bugs.

**Comment by lisaac** [comment]
> Yes I guess it has been abandoned
@haze1986 
No.
It's in stable phase, so there aren't many commits.

> I ask because in OpenWrt there is an even older version that has bugs.
@castillofrancodamian
Yes, so I recommend using this repository instead of Offical OpenWrt.

**Comment by castillofrancodamian** [comment]
If the version in this repository is stable, why wasn't it upgraded upstream.
