### ISSUE TITLE
Bug：OpenWrt 21.02.3 r16554编译最新的luci-app-dockerman没有在Luci界面显示

### ISSUE THREAD

**Issue by wazzx** [lisaac/luci-app-dockerman#153]
**问题描述**
如图示：luci界面没有dockerman的任何选项！也就是说luci-app-dockerman在luci界面没有显示出来，希望老大有空快点来修复一下这个bug吧！

使用 dockerman 时遇到的问题

**使用命令行**
同样的操作使用命令行的结果

**版本信息:**
 - openwrt 版本：OpenWrt 21.02.3 r16554-1d4dea6d4f 

 - luci 版本：LuCI openwrt-21.02 branch git-22.213.35964-87836ca
 - docker daemon 版本：dockerd	20.10.17-1
 - dockerman 版本：v0.5.25
![image](https://user-images.githubusercontent.com/60512548/187680523-5daa6779-7689-4ef1-a001-47af5e5a43d1.png)

**Comment by GameKyuubi** [comment]
![Untitled](https://user-images.githubusercontent.com/6174313/206128772-611344eb-76b4-43c8-a61f-00b7c1dec6a3.png)

same problem

**Comment by haldi4803** [comment]
> 

Don't install v0.5.13 from OPKG, install v0.5.25 from Github.

**Comment by JKSTAFF** [comment]
> 另外 docker 的 Dropdown 好像坏了
luci的docker下拉菜单是不是已经不显示了？

**Comment by c0ldtech** [comment]
> > 另外 docker 的 Dropdown 好像坏了
> 
> luci的docker下拉菜单是不是已经无法正常显示了？

Any idea when this will be fixed? It's not a major issue, just annoying. Maybe there even is some way to manually fix this for the time being? Does anybody know?

**Comment by c0ldtech** [comment]
> 
> Any idea when this will be fixed? It's not a major issue, just annoying. Maybe there even is some way to manually fix this for the time being? Does anybody know?

FYI: It seems this has now been fixed with luci-app-dockerman v0.5.13.

**Comment by AxisRay** [comment]
> FYI: It seems this has now been fixed with luci-app-dockerman v0.5.13.
No
![image](https://user-images.githubusercontent.com/6546326/217906002-ddd48007-b442-4e80-ab52-53ac686d5027.png)
![image](https://user-images.githubusercontent.com/6546326/217906084-ef719257-21f3-46f0-9d59-33de657e7ee8.png)

**Comment by c0ldtech** [comment]
It is working for me, but I am on 22.03, so maybe there's a difference:

![image](https://user-images.githubusercontent.com/84471262/218030939-fe5cbfc9-b54b-42fa-9316-833069c5eddd.png)

**Comment by haldi4803** [comment]
Might be the issue.


Architecture | ARMv8 Processor rev 4
-- | --
Target Platform | mediatek/filogic
Firmware Version | OpenWrt SNAPSHOT r21995-059263dd6e / LuCI Master git-23.017.73484-3c2b35c
Kernel Version | 5.15.91

**Comment by Bunnui** [comment]
> ![Untitled](https://user-images.githubusercontent.com/6174313/206128772-611344eb-76b4-43c8-a61f-00b7c1dec6a3.png)
> 
> 同样的问题

+1，OpenWrt22.03.03

**Comment by Bunnui** [comment]
![image](https://user-images.githubusercontent.com/37466008/223505875-f18e977f-4c29-48ac-a7fc-4094ef5d479d.png)

OpenWrt（SNAPSHOT r22241-acb189179c）
Kernel Version：5.15.98

**Comment by cyqtmxk** [comment]
22.03同样的问题：
![image](https://user-images.githubusercontent.com/10682818/224352636-df40e3a7-3ceb-4efc-b5bb-7c1027bfd471.png)
![image](https://user-images.githubusercontent.com/10682818/224352858-11141266-fb40-45e6-9cc6-1d6625429997.png)

**Comment by samlin39** [comment]
供参考
https://github.com/lisaac/luci-app-dockerman/issues/140#issuecomment-1493037277
