### ISSUE TITLE
openwrt启动容器报错

### ISSUE THREAD

**Issue by liu-dc** [lisaac/luci-app-dockerman#154]
**问题描述**
openwrt启动容器报错：
Containers: start bitwarden...code:500 OCI runtime create failed: container_linux.go:349: starting container process caused "seccomp: config provided but seccomp not supported": unknown

使用 dockerman 时遇到的问题

**使用命令行**
同样的操作使用命令行的结果

**版本信息:**
 - openwrt 版本：19.03.8
 - luci 版本：
 - docker daemon 版本：
 - dockerman 版本：

**Comment by lisaac** [comment]
从结果来看应该是没有模块导致的，请再检查一下。
https://github.com/lisaac/luci-app-dockerman/issues/36#issuecomment-612375880
