### ISSUE TITLE
无法创建容器

### ISSUE THREAD

**Issue by achinese888** [lisaac/luci-app-dockerman#155]
**Use CLI**
docker run -d
--name jellyfin
-p 8096:8096
--device=/dev/dri/renderD128
--device /dev/dri/card0:/dev/dri/card0 \
--restart unless-stopped
jellyfin/jellyfin
![image](https://user-images.githubusercontent.com/89327727/189584057-78b6f670-0c64-4c16-b2f2-7d3f9f8efb4e.png)

The result of using the command line
 - openwrt version: OpenWrt R22.9.1 / LuCI Master (git-22.254.18307-f40a385)
 - docker daemon version: 1.41
 - dockerman version: 20.10.18

**Comment by lisaac** [comment]
先使用命令行试下，能否成功

**Comment by achinese888** [comment]
不行啊，好像是新版本的问题，刚换固件

**Comment by achinese888** [comment]
root@OpenWrt:~# docker pull jellyfin/jellyfin
Using default tag: latest
latest: Pulling from jellyfin/jellyfin
1efc276f4ff9: Downloading 
709cceda6a59: Download complete 
f6de91e91a10: Download complete 
9713c087dd1e: Download complete 
latest: Pulling from jellyfin/jellyfin
1efc276f4ff9: Pull complete 
709cceda6a59: Extracting [==================================================>]  242.5MB/242.5MB
f6de91e91a10: Download complete 
9713c087dd1e: Download complete 
failed to register layer: operation not supported

**Comment by hehe1874** [comment]
https://github.com/luolongfei/freenom/issues/185#issuecomment-1425210891
