### ISSUE TITLE
如何开启默认bridge网络的IPv6支持

### ISSUE THREAD

**Issue by Primimy** [lisaac/luci-app-dockerman#156]
根据[docker官方的教程](https://docs.docker.com/config/daemon/ipv6/)已经在/etc/docker/daemon.json中加入支持ipv6的选项
```
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80",
  "experimental": true,
  "ip6tables": true
}
```
重启docker进程后依然无法连接到ipv6，查看docker网络如下
![image](https://user-images.githubusercontent.com/38491737/199190914-d58d7f57-0687-4974-b08b-7f9dacd3566b.png)，
默认的网络没有开启相关选项，
检查进程后发现启动配置文件为/tmp/dockerd/deamon.json，猜测这个文件是由/etc/init.d/dockerd生成的，求教如何开启。

**Comment by lisaac** [comment]
两个方法选其一：
- 删除/etc/config/dockerd配置文件以启用/etc/docker/daemon.json
- 修改/etc/config/dockerd内相关配置

**Comment by Primimy** [comment]
我修改了/etc/config/dockerd
![image](https://user-images.githubusercontent.com/38491737/199390400-bced69ad-1cf5-44b0-ba4c-8a43a935cc80.png)
查询进程中有在运行，但是重启后连接不到守护进程，可以给出一个例子吗

**Comment by Primimy** [comment]
尝试在/etc/config/dockerd中引入
`'option alt_config_file '/etc/docker/daemon.json'`
并在/etc/docker/daemon.json中修改后成功
