### ISSUE TITLE
使用大雕源码编译，luci仓库~只要一开启远程实例，overview就报错。

### ISSUE THREAD

**Issue by pikachullk** [lisaac/luci-app-dockerman#159]
开启远程实例的话，一点击概述就提示
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/docker/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/dockerman/overview.lua:127: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:477: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

其余页面正常

**Comment by pikachullk** [comment]
安装使用0.5.23-2是正常的~

**Comment by lisaac** [comment]
远程实例是什么平台什么版本docker？

**Comment by pikachullk** [comment]
> 远程实例是什么平台什么版本docker？

X86平台的，应该是docker-ce
版本是
Docker version 23.0.1, build a5ee5b1
管理界面我用的是portainer

**Comment by weilai-all** [comment]
不想麻烦可以临时注释掉 /usr/lib/lua/luci/model/cbi/dockerman/overview.lua 127-129，感觉没啥影响

**Comment by pikachullk** [comment]
> 不想麻烦可以临时注释掉 /usr/lib/lua/luci/model/cbi/dockerman/overview.lua 127-129，感觉没啥影响

虽然行数不同~但是按照你这个思路我照着修改了。。。还真可以~感谢大佬~
