### ISSUE TITLE
升级后4G内存变2G

### ISSUE THREAD

**Issue by lloyd18** [lisaac/luci-app-dockerman#16]
下面翻译有误
![1](https://user-images.githubusercontent.com/10294460/75047989-c1539f80-5502-11ea-8c32-6fa4d7e64b39.jpg)

**Comment by lloyd18** [comment]
还有你README.md里的指令只会下载一个Makefile文件 没有源码

**Comment by lisaac** [comment]
#15
对，makefile 会下载源码

**Comment by lisaac** [comment]
最新版本已经改用jsonc
如果没有修复https://github.com/openwrt/luci/issues/3293
就是你现在这种状况
