### ISSUE TITLE
Networks attempt to index field 'Options'

### ISSUE THREAD

**Issue by xiaoyao9184** [lisaac/luci-app-dockerman#160]
**Describe the bug**

access `http://<host>/cgi-bin/luci/admin/docker/networks` return

```
/usr/lib/lua/luci/model/cbi/dockerman/networks.lua:36: attempt to index field 'Options' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/cbi/dockerman/networks.lua:36: in function 'get_networks'
	/usr/lib/lua/luci/model/cbi/dockerman/networks.lua:48: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1531: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1059: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>
```

**Use CLI**
no cli

**Version information**
 - openwrt version: OpenWrt 22.03.3 r20028-43d71ad93e
 - luci version: LuCI openwrt-22.03 branch git-23.035.77007-790b738
 - docker daemon version: 20.10.22-1
 - dockerman version: v0.5.13-20230114

**Comment by lisaac** [comment]
please try the dockerman in this repo.

**Comment by xiaoyao9184** [comment]
same issue as https://github.com/lisaac/luci-app-dockerman/issues/153 when update to [v0.5.25](https://github.com/lisaac/luci-app-dockerman/releases/tag/v0.5.25)
