### ISSUE TITLE
OP版overview界面报错

### ISSUE THREAD

**Issue by Speechless22** [lisaac/luci-app-dockerman#161]
**问题描述**

web页192.168.1.1/cgi-bin/luci/admin/docker/overview报错

Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/model/cbi/dockerman/overview.lua:68: bad argument #1 to 'ipairs' (table expected, got nil)

In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function [arrow function] (/usr/share/ucode/luci/dispatcher.uc:794:4)
  called from function render ([C])
  called from function render_action (/usr/share/ucode/luci/dispatcher.uc:768:24)
  called from function run_action (/usr/share/ucode/luci/dispatcher.uc:795:4)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:998:48)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^

**版本信息:**
 官方源最近编译的
 - openwrt 版本：OpenWrt SNAPSHOT r22400-1558bbd116 / LuCI Master git-23.074.82619-6ad6a24
 - luci 版本：git-23.051.66410-a505bb1
 - docker daemon 版本：23.0.1-1
 - dockerman 版本：v0.5.13-20230114

**Comment by davidtall** [comment]
same issue,LUCI 22.03

**Comment by cyclc77** [comment]
同样的问题，更新github版本就没了状态下拉栏，用了openwrt官方源里的概述界面就错误。

**Comment by davidtall** [comment]
可以试试我修复的分支 ，目前测试在lean 和官方22.03 都能用 https://github.com/davidtall/luci-app-dockerman

**Comment by cyclc77** [comment]
> 可以试试我修复的分支 ，目前测试在lean 和官方22.03 都能用 https://github.com/davidtall/luci-app-dockerman

重新编译了，官方版本开发版 显示错误
Docker 版本 | Can NOT connect to docker daemon, please check!!

**Comment by lisaac** [comment]
最近太忙，有能力的望提交PR，预计会在6月回来

**Comment by davidtall** [comment]
> > 可以试试我修复的分支 ，目前测试在lean 和官方22.03 都能用 https://github.com/davidtall/luci-app-dockerman
> 
> 重新编译了，官方版本开发版 显示错误 Docker 版本 | Can NOT connect to docker daemon, please check!!

能贴个详细的日志吗？是 https://github.com/openwrt/openwrt 的master分支吗？

**Comment by cyclc77** [comment]
> > > 可以试试我修复的分支 ，目前测试在lean 和官方22.03 都能用 https://github.com/davidtall/luci-app-dockerman
> > 
> > 
> > 重新编译了，官方版本开发版 显示错误 Docker 版本 | Can NOT connect to docker daemon, please check!!
> 
> 能贴个详细的日志吗？是 https://github.com/openwrt/openwrt 的master分支吗？可否把.config 文件上传一下，我编译试试

已经更换原始固件了。是master分支，因为官方22.03跟lean用自己的dockerman都是没有错误的，只有用master分支时候，安装dockerman才会报错。我是直接替换的官方luci库的luci-app-dockerman然后编译的，就一直提示docker未启动

**Comment by davidtall** [comment]
> > > > 可以试试我修复的分支 ，目前测试在lean 和官方22.03 都能用 https://github.com/davidtall/luci-app-dockerman
> > > 
> > > 
> > > 重新编译了，官方版本开发版 显示错误 Docker 版本 | Can NOT connect to docker daemon, please check!!
> > 
> > 
> > 能贴个详细的日志吗？是 https://github.com/openwrt/openwrt 的master分支吗？可否把.config 文件上传一下，我编译试试
> 
> 已经更换原始固件了。是master分支，因为官方22.03跟lean用自己的dockerman都是没有错误的，只有用master分支时候，安装dockerman才会报错。我是直接替换的官方luci库的luci-app-dockerman然后编译的，就一直提示docker未启动

我用immortalwrt 的master 分支编译，没有问题。改天有空再用官方的master分支试试

**Comment by davidtall** [comment]
官方 master 分支报错,dockerd 启动失败
'''
WARN[2023-04-23T07:31:05.555264508Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
WARN[2023-04-23T07:31:05.555840832Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
ERRO[2023-04-23T07:31:05.557801396Z] failed to initialize a tracing processor "otlp"  error="no OpenTelemetry endpoint: skip plugin"
ERRO[2023-04-23T07:31:05.590433498Z] failed to mount overlay: invalid argument     storage-driver=overlay2
ERRO[2023-04-23T07:31:05.590597387Z] exec: "fuse-overlayfs": executable file not found in $PATH  storage-driver=fuse-overlayfs
failed to start daemon: Devices cgroup isn't mounted
'''
然后我试了使用官方的luci-app-dockerman，docker菜单只显示了一个“配置”这个菜单项，启动dockerd 也是报同样的错误。所以这个问题并不是luci-app-dockerman 的问题，是官方dockerd 的问题。不建议使用master分支，还是用22.03稳定版吧，或者用immortalwrt 的master 分支，我试了没有问题

<img width="983" alt="image" src="https://user-images.githubusercontent.com/9320941/233826310-c3a7c4f5-1a63-444a-9eab-7cc1d0ae5838.png">

**Comment by cyclc77** [comment]
> 官方 master 分支报错,dockerd 启动失败
> 
> ```
> WARN[2023-04-23T07:31:05.555264508Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
> WARN[2023-04-23T07:31:05.555840832Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
> ERRO[2023-04-23T07:31:05.557801396Z] failed to initialize a tracing processor "otlp"  error="no OpenTelemetry endpoint: skip plugin"
> ERRO[2023-04-23T07:31:05.590433498Z] failed to mount overlay: invalid argument     storage-driver=overlay2
> ERRO[2023-04-23T07:31:05.590597387Z] exec: "fuse-overlayfs": executable file not found in $PATH  storage-driver=fuse-overlayfs
> failed to start daemon: Devices cgroup isn't mounted
> ```
> 
> 然后我试了使用官方的luci-app-dockerman，docker菜单只显示了一个“配置”这个菜单项，启动dockerd 也是报同样的错误。所以这个问题并不是luci-app-dockerman 的问题，是官方dockerd 的问题。不建议使用master分支，还是用22.03稳定版吧，或者用immortalwrt 的master 分支，我试了没有问题
> 
> <img alt="image" width="983" src="https://user-images.githubusercontent.com/9320941/233826310-c3a7c4f5-1a63-444a-9eab-7cc1d0ae5838.png">

我感觉是docker 升级版本导致的吧。docker可能更新了API或者删除了一些功能导致的。
openwrt官方master分支用的docker是23.0.1
openwrt官方22.03是20.10.22
大雕的lede用的是20.10.18
这是更新发布文档，小白看不懂，希望大佬研究下
https://github.com/moby/moby/releases/tag/v23.0.0

**Comment by WYC-2020** [comment]
> > 官方 master 分支报错,dockerd 启动失败
> > ```
> > WARN[2023-04-23T07:31:05.555264508Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
> > WARN[2023-04-23T07:31:05.555840832Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
> > ERRO[2023-04-23T07:31:05.557801396Z] failed to initialize a tracing processor "otlp"  error="no OpenTelemetry endpoint: skip plugin"
> > ERRO[2023-04-23T07:31:05.590433498Z] failed to mount overlay: invalid argument     storage-driver=overlay2
> > ERRO[2023-04-23T07:31:05.590597387Z] exec: "fuse-overlayfs": executable file not found in $PATH  storage-driver=fuse-overlayfs
> > failed to start daemon: Devices cgroup isn't mounted
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后我试了使用官方的luci-app-dockerman，docker菜单只显示了一个“配置”这个菜单项，启动dockerd 也是报同样的错误。所以这个问题并不是luci-app-dockerman 的问题，是官方dockerd 的问题。不建议使用master分支，还是用22.03稳定版吧，或者用immortalwrt 的master 分支，我试了没有问题
> > <img alt="image" width="983" src="https://user-images.githubusercontent.com/9320941/233826310-c3a7c4f5-1a63-444a-9eab-7cc1d0ae5838.png">
> 
> 我感觉是docker 升级版本导致的吧。docker可能更新了API或者删除了一些功能导致的。 openwrt官方master分支用的docker是23.0.1 openwrt官方22.03是20.10.22 大雕的lede用的是20.10.18 这是更新发布文档，小白看不懂，希望大佬研究下 https://github.com/moby/moby/releases/tag/v23.0.0

这就是你没有配置镜像加速的时候 没有返回值而已，应该是新的docker和老的有那么一点区别，应该老的会返回-而已，这个稍微修复一下即可，顺便我升级到了docker最新
![image](https://github.com/lisaac/luci-app-dockerman/assets/34025388/a08f963f-c538-4575-8784-5a2cc616feb3)


如此修改 
if docker_info.body.RegistryConfig.Mirrors ~= nil then
		for i, v in ipairs(docker_info.body.RegistryConfig.Mirrors) do
			docker_info_table['9RegistryMirrors']._value = docker_info_table['9RegistryMirrors']._value == "-" and v or (docker_info_table['9RegistryMirrors']._value .. ", " .. v)
		end
	else
		docker_info_table['9RegistryMirrors']._value =  "-"
	end

**Comment by Joee-D** [comment]
> > 官方 master 分支报错,dockerd 启动失败
> > ```
> > WARN[2023-04-23T07:31:05.555264508Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
> > WARN[2023-04-23T07:31:05.555840832Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
> > ERRO[2023-04-23T07:31:05.557801396Z] failed to initialize a tracing processor "otlp"  error="no OpenTelemetry endpoint: skip plugin"
> > ERRO[2023-04-23T07:31:05.590433498Z] failed to mount overlay: invalid argument     storage-driver=overlay2
> > ERRO[2023-04-23T07:31:05.590597387Z] exec: "fuse-overlayfs": executable file not found in $PATH  storage-driver=fuse-overlayfs
> > failed to start daemon: Devices cgroup isn't mounted
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后我试了使用官方的luci-app-dockerman，docker菜单只显示了一个“配置”这个菜单项，启动dockerd 也是报同样的错误。所以这个问题并不是luci-app-dockerman 的问题，是官方dockerd 的问题。不建议使用master分支，还是用22.03稳定版吧，或者用immortalwrt 的master 分支，我试了没有问题
> > <img alt="image" width="983" src="https://user-images.githubusercontent.com/9320941/233826310-c3a7c4f5-1a63-444a-9eab-7cc1d0ae5838.png">
> 
> 我感觉是docker 升级版本导致的吧。docker可能更新了API或者删除了一些功能导致的。 openwrt官方master分支用的docker是23.0.1 openwrt官方22.03是20.10.22 大雕的lede用的是20.10.18 这是更新发布文档，小白看不懂，希望大佬研究下 https://github.com/moby/moby/releases/tag/v23.0.0

我也遇到了这个问题，尝试了下找到了一个解决方法：

修改cgroupfs-mount文件
 使用命令：
vi /etc/init.d/cgroupfs-mount
 注释掉其中的这三行：
``` python
if mountpoint -q /sys/fs/cgroup; then
	umount /sys/fs/cgroup/
fi
```
