### ISSUE TITLE
今天的合并更新CPU 使用率和内存使用率显示异常

### ISSUE THREAD

**Issue by umlka** [lisaac/luci-app-dockerman#163]
**问题描述**

今天的合并更新后, lean lede X86固件容器CPU 使用率显示为 0.00 / 100 (0%) 内存使用率显示为 NaN undefined / NaN undefined (0%)

luci-lib-docker和luci-app-dockerman均是拉取的大佬的最新版

**版本信息:**
 - openwrt 版本：OpenWrt R23.4.1 / LuCI Master (git-23.109.50273-11b9572)
 - luci 版本：18.06
 - docker daemon 版本：
 - dockerman 版本：v0.5.25-1

**Comment by kxdn3** [comment]
6.1内核会这样，目前5.15正常

**Comment by kxdn3** [comment]
还没修复噢

**Comment by devnakx** [comment]
同样是这个问题啊，重启也没用
