### ISSUE TITLE
编译后错误问题

### ISSUE THREAD

**Issue by cjlhll** [lisaac/luci-app-dockerman#168]
**问题描述**

你好，我是N1设备，使用github 云编译，启动N1后，docker提示无法连接到docker守护进程，我手动启动后，Docker根目录也就409MB，然后N1重启后docker又起不来了，还是提示docker提示无法连接到docker守护进程。下面是我的编译步骤。麻烦大佬帮我看看。

**使用命令行**
同样的操作使用命令行的结果

**版本信息:**
 - openwrt 版本：
 - luci 版本：
 - docker daemon 版本：
 - dockerman 版本：
![photo_2023-06-30_22-40-14](https://github.com/lisaac/luci-app-dockerman/assets/26736892/866caac9-945d-430f-a20f-c5bdd20a09f2)
![photo_2023-06-30_22-40-09](https://github.com/lisaac/luci-app-dockerman/assets/26736892/abaf8eba-a0f0-42a8-9840-4502baa6570f)
![photo_2023-06-30_22-40-04](https://github.com/lisaac/luci-app-dockerman/assets/26736892/4e998e89-cd48-42c1-bd6f-8161bc1073cb)
![photo_2023-06-30_22-39-59](https://github.com/lisaac/luci-app-dockerman/assets/26736892/bb1dd73e-9877-4a86-b1c0-34cdc3a5e731)

**Comment by lisaac** [comment]
这个结果应该是 dockerd 没有启动，可以尝试手动在命令行运行 dockerd ，看看是什么问题

**Comment by cjlhll** [comment]
我手动启动后，可以正常启动，那为什么没有自动启动呢？在系统-启动项里dockerd默认是禁用的，但是docker根目录只有409M呢，我刷的别人的固件能正常显示我U盘剩余的26G的空间。编译的时候需要特殊配置吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月4日(星期二) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lisaac/luci-app-dockerman] 编译后错误问题 (Issue #168)





 
这个结果应该是 dockerd 没有启动，可以尝试手动在命令行运行 dockerd ，看看是什么问题

**Comment by lisaac** [comment]
建议搜索一下，关键词 「overlay 扩容」
