### ISSUE TITLE
无法进入网络查看页面

### ISSUE THREAD

**Issue by yu1ec** [lisaac/luci-app-dockerman#185]
**问题描述**
基于esir高大全2024版本的openwrt安装的docker环境，进入docker->网络 然后直接报错
```
/usr/lib/lua/luci/dispatcher.lua:482: Failed to execute cbi dispatcher target for entry '/admin/docker/networks'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/dockerman/networks.lua:44: attempt to index field 'Config' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:482: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>
```
 
**使用命令行**
同样的操作使用命令行的结果
![image](https://github.com/lisaac/luci-app-dockerman/assets/2928867/dd6c77f2-c54a-409d-bce6-806411db3385)

--

<br class="Apple-interchange-newline">

**版本信息:**
 - openwrt 版本：OpenWrt R24.2.2 GDQ V1 [2024] Compiled by eSir
 - luci 版本：LuCI Master (git-24.088.44804-94aca21)
 - docker daemon 版本：Docker version 27.0.2, build e953d76
 - dockerman 版本：v0.5.26

**Comment by lisaac** [comment]
```
wget -O /usr/lib/lua/luci/model/cbi/dockerman/networks.lua https://raw.githubusercontent.com/lisaac/luci-app-dockerman/master/applications/luci-app-dockerman/luasrc/model/cbi/dockerman/networks.lua
```
然后重新测试一下

**Comment by yu1ec** [comment]
可以了，没毛病。
