### ISSUE TITLE
OpenWrt重启后LuCI界面的Docker菜单下只有配置一栏

### ISSUE THREAD

**Issue by 2580m** [lisaac/luci-app-dockerman#187]
**Describe the bug**
当我重启后，LuCI界面的Docker菜单下只剩配置一栏

**Use CLI**
我尝试过/etc/init.d/dockerd restart，但好像我必须重新安装dockerman才行
**Version information**
 - openwrt version:23.05
 - luci version:openwrt-23.05 branch
 - docker daemon version:27.03-1(是指dockerd吗?)
 - dockerman version:v0.5.13-20240317

问题复现：
opkg update
opkg install luci-lib-docker dockerd luci-lib-jsonc docker --force-depends
docker --version
opkg install luci-app-dockerman
opkg install luci-i18n-dockerman-zh-cn

ln -s /etc/init.d/dockerd /etc/rc.d/S99docker

docker pull cym1102/nginxwebui:latest
docker run -itd --restart=always --name=nginxWebUI -v /home/nginxWebUI:/home/nginxWebUI -e BOOT_OPTIONS="--server.port=8080" --privileged=true --net=host  cym1102/nginxwebui:latest /bin/bash

docker update --restart=always nginxWebUI

reboot

最后附上我使用的固件地址，希望有帮助
https://github.com/2580m/OpenWrt-K/releases/download/v24.07.07-19(x86-64)-(v23.05.3)/openwrt-x86-64-generic-ext4-combined-efi.img.gz

**Comment by 2580m** [comment]
疑似与几个ipk冲突

**Comment by 2580m** [comment]
确定是ipk问题，自编译安装后一切正常

**Comment by nxygen** [comment]
> 确定是ipk问题，自编译安装后一切正常

你好，麻烦问下，我也遇到同样的问题，想知道是与哪几个包冲突

**Comment by 2580m** [comment]
> > 确定是ipk问题，自编译安装后一切正常
> 
> 你好，麻烦问下，我也遇到同样的问题，想知道是与哪几个包冲突

我去，不好意思，我忘了，现在软路由已经挂在那不折腾了，果咩

**Comment by 2580m** [comment]
> > 确定是ipk问题，自编译安装后一切正常
> 
> 你好，麻烦问下，我也遇到同样的问题，想知道是与哪几个包冲突

想了下当时好像是因为dockerd无法启动，然后就去检查docker了，你也可以监测一下docker的状态看看

**Comment by nxygen** [comment]
> > > 确定是ipk问题，自编译安装后一切正常
> > 
> > 
> > 你好，麻烦问下，我也遇到同样的问题，想知道是与哪几个包冲突
> 
> 想了下当时好像是因为dockerd无法启动，然后就去检查docker了，你也可以监测一下docker的状态看看

感谢感谢，不过我是把官方源的软件包删掉拉取的最新dockerman又正常了
