### ISSUE TITLE
请问怎么更新容器呢，不想每次删除镜像再重新啦，怎么咋原始数据上更新docker容器

### ISSUE THREAD

**Issue by maomaoyan** [lisaac/luci-app-dockerman#189]
**问题描述**

使用 dockerman 时遇到的问题

**使用命令行**
同样的操作使用命令行的结果

**版本信息:**
 - openwrt 版本：
 - luci 版本：
 - docker daemon 版本：
 - dockerman 版本：

**Comment by lisaac** [comment]
点击升级按钮
