### ISSUE TITLE
GITHUB_TOKEN:求教

### ISSUE THREAD

**Issue by hong0980** [lisaac/luci-app-dockerman#19]
问大佬看了自动发布这个GITHUB_TOKEN到最后无法通过，在那里布置这个GITHUB_TOKEN才能通过。

**Comment by hong0980** [comment]
![2020-2-28 13-11-4](https://user-images.githubusercontent.com/32021831/75512319-f8a6dc80-5a2b-11ea-9774-175f4fc9dd09.png)

**Comment by lisaac** [comment]
具体原因我也不太清楚，请查看项目主页
https://github.com/actions/create-release

**Comment by hong0980** [comment]
谢谢
