### ISSUE TITLE
luci crash

### ISSUE THREAD

**Issue by IoT6** [lisaac/luci-app-dockerman#2]
Hello. After installing the package:

/usr/lib/lua/luci/model/uci.lua:302: attempt to call method 'get_all' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/uci.lua:302: in function </usr/lib/lua/luci/model/uci.lua:284>
	(tail call): ?
	/usr/lib/lua/luci/model/docker.lua:28: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/dockerman.lua:11: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:654: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:681: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:347: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:208: in function </usr/lib/lua/luci/dispatcher.lua:207>

Am I doing something wrong? Assembled in x86 SDK.

**Comment by lisaac** [comment]
Please be clear about the environment you use? Which branch?

And need to be reminded, you need have docker in your openwrt(like lean's opnewrt)
or using  [LuCI-in-docker](https://github.com/lisaac/luci-in-docker).
