### ISSUE TITLE
Docker Events 异常

### ISSUE THREAD

**Issue by lloyd18** [lisaac/luci-app-dockerman#20]
１.Docker这个大标题如果是作为整个插件的标题 我觉得放在顶部会不会好看一些，而”事件“这个选项下是Docker Events ，如果作为选项下对应的英文标题那前几个选项是不是也得加上相应的英文标题
２.导入镜像下的输入框和拉取镜像的输入框是否可以对齐一下。

**Comment by lloyd18** [comment]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/75520072-a079d580-5a3f-11ea-8a51-c66f90e03692.jpg)

**Comment by lisaac** [comment]
1. 请参考本仓库的源码或 ipk
2. 已经在最新提交中修正这个问题（还没有提交版本号），或使用 bootstrap 主题

**Comment by lisaac** [comment]
刚刚忘记 push，已经 push

**Comment by lloyd18** [comment]
> 刚刚忘记 push，已经 push

明白了，不过好像又发现点小问题，打开事件页面会有小概率报错，你在事件页面一直刷新试试
难道是我分类到services下才导致的问题？




![1](https://user-images.githubusercontent.com/10294460/75537435-2dc62580-5a52-11ea-87fb-edb9781c86f0.jpg)

**Comment by lisaac** [comment]
我这边没有碰到
events 获取速度相对较慢，可能会出现一些问题，也是代码不够健壮，回头加一些判断防止出错吧

**Comment by lloyd18** [comment]
> 我这边没有碰到
> events 获取速度相对较慢，可能会出现一些问题，也是代码不够健壮，回头加一些判断防止出错吧

确实是和日志多少有关，如果没有日志怎么刷新都不会报错，大概有20条左右日志就会出错

**Comment by lisaac** [comment]
日志多了之后是100%复现吗？
另外，我这边满日志都没这问题

**Comment by lloyd18** [comment]
怎么说呢 直接录个GIF给你吧
![1](https://user-images.githubusercontent.com/10294460/75541321-ab8d2f80-5a58-11ea-87b5-18dc86acf0a1.gif)

**Comment by lloyd18** [comment]
> 日志多了之后是100%复现吗？
> 另外，我这边满日志都没这问题

刚刷完机没有日志的时候怎么刷新都没出错，换过浏览器测试，可以排除浏览器问题

**Comment by lisaac** [comment]
嗯，有条件试下，conrainer中的log页面吗

**Comment by lloyd18** [comment]
> 嗯，有条件试下，conrainer中的log页面吗

不是，就是events这个页面

**Comment by lisaac** [comment]
我的意思是，那个页面是否会出现类似情况？

**Comment by lloyd18** [comment]
> 我的意思是，那个页面是否会出现类似情况？

刚试了一下，如果在这个页面一直刷新会小概率卡住，无法刷新

**Comment by lloyd18** [comment]
![2](https://user-images.githubusercontent.com/10294460/75543775-8f3fc180-5a5d-11ea-9501-da49f174c2ad.gif)

**Comment by lisaac** [comment]
多次测试没有发现你说的问题，能做的就是提高代码健壮，等其他人报是否有类似情况

**Comment by aizhiqi** [comment]
有人和我一样吗？
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled
把镜像改为去163、USTC、腾讯拉取都会报这个错
在/etc/docker/daemon.json加上"registry-mirrors": ["https://registry.docker-cn.com"]仍然没有解决
