### ISSUE TITLE
bridge模式下docker无法解析域名

### ISSUE THREAD

**Issue by YYiiEt** [lisaac/luci-app-dockerman#21]
大概不是app的问题，但还是想请教一下大佬。
树莓派固定ip做旁路由，docker可以ping通ip，但无法解析域名。
参考过 #6 的设置，但似乎不是同一个问题。
![Snipaste_2020-02-29_14-25-08](https://user-images.githubusercontent.com/60560292/75602540-46d9df80-5b01-11ea-8887-0230ed10d5f0.png)
指定dns问题依旧
![Snipaste_2020-02-29_14-36-35](https://user-images.githubusercontent.com/60560292/75602567-81437c80-5b01-11ea-8790-674c6ee61ae4.png)

**Comment by lisaac** [comment]
docker 服务端的问题，没碰到过这种情况，建议进入容器后手动修改 resolv.conf
```
echo "nameserver 114.114.114.114" > /etc/resolv.conf
ping qq.com
```

**Comment by YYiiEt** [comment]
本地dns是114，宿主机也能正常上网，唯独docker异常。
![Snipaste_2020-02-29_15-25-59](https://user-images.githubusercontent.com/60560292/75603302-003bb380-5b08-11ea-8f00-838438c66398.png)
小白搜索了一圈也没弄懂是什么情况，貌似也不是防火墙的问题
![Snipaste_2020-02-29_15-39-16](https://user-images.githubusercontent.com/60560292/75603491-ccfa2400-5b09-11ea-992e-425e751db143.png)

**Comment by YYiiEt** [comment]
补充一下nslookup提示DNS服务器拒绝为请求服务
![Snipaste_2020-02-29_17-14-48](https://user-images.githubusercontent.com/60560292/75604857-1c475100-5b18-11ea-9a77-dd343be46b9c.png)
