### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled

### ISSUE THREAD

**Issue by aizhiqi** [lisaac/luci-app-dockerman#23]
有人和我一样吗？
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled
把镜像改为去163、USTC、腾讯拉取都会报这个错
在/etc/docker/daemon.json加上"registry-mirrors": ["https://registry.docker-cn.com"]仍然没有解决

**Comment by lisaac** [comment]
与插件无关联
