### ISSUE TITLE
最新版本在配置时无法显示luci-app-dockerman，只显示了ttyd和docker的配置选项！

### ISSUE THREAD

**Issue by zxlhhyccc** [lisaac/luci-app-dockerman#25]
我是官方19.07的openwrt，这个情况下能否编译luci？
![image](https://user-images.githubusercontent.com/45259624/76144756-62735600-60be-11ea-925d-dbf836b56090.png)
![image](https://user-images.githubusercontent.com/45259624/76144760-7028db80-60be-11ea-8533-947f0d5781af.png)

**Comment by lisaac** [comment]
没有选项就没法打包
luci-lib-jsonc
luci-lib-docker是否安装

**Comment by zxlhhyccc** [comment]
> 没有选项就没法打包
> luci-lib-jsonc
> luci-lib-docker是否安装

已找到原因，不是你说的两个包问题，是makefile的代码中DEPENDS:=+....+PACKAGE_$(PKG_NAME)_INCLUDE_docker-ce:docker-ce +......多了-ce,改为PACKAGE_$(PKG_NAME)_INCLUDE_docker:docker-ce配置中正常显示。。。
![image](https://user-images.githubusercontent.com/45259624/76145842-8e93d480-60c8-11ea-8278-8a4905ebd8e8.png)

**Comment by lisaac** [comment]
你改掉后，应该就没法选上docker-ce了
官方源需要自己配置 Utilities  --->  Kernel features for Docker  ---> 下面的选项，docker-ce 才能正常勾选
