### ISSUE TITLE
编译报错，大雕源码

### ISSUE THREAD

**Issue by lloyd18** [lisaac/luci-app-dockerman#26]
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring luci-i18n-nlbwmon-zh-cn.
Configuring dnsmasq-full.
Setting flags for package libc to hold.
Setting flags for package libgcc to hold.
Setting flags for package libpthread to hold.
Setting flags for package librt to hold.
cp -fpR /home/lan/lede/build_dir/target-x86_64_musl/root-x86 /home/lan/lede/build_dir/target-x86_64_musl/root.orig-x86
/home/lan/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/luci-app-dockerman.postinst-pkg: line 2: uci: command not found
/home/lan/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/luci-app-dockerman.postinst-pkg: line 3: uci: command not found
/home/lan/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/luci-app-dockerman.postinst-pkg: line 5: /etc/init.d/uhttpd: No such file or directory
postinst script ./usr/lib/opkg/info/luci-app-dockerman.postinst has failed with exit code 127
make[2]: *** [package/Makefile:71: package/install] Error 1
make[2]: Leaving directory '/home/lan/lede'
make[1]: *** [package/Makefile:108: /home/lan/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/lan/lede'
make: *** [/home/lan/lede/include/toplevel.mk:227：world] 错误 2
lan@ubuntu:~/lede$

**Comment by lisaac** [comment]
下个版本修复

**Comment by lloyd18** [comment]
> 下个版本修复

官方源码会报错吗？

**Comment by zxlhhyccc** [comment]
> > 下个版本修复
> 
> 官方源码会报错吗？
> 
> 好吧，试了，官方源码也是报错

好像是缺依赖吧

**Comment by lisaac** [comment]
fixed
