### ISSUE TITLE
Docker Daemon / Dockerman 设置页面异常

### ISSUE THREAD

**Issue by adaaaaaa** [lisaac/luci-app-dockerman#28]
root@OpenWrt:/mnt/sda1/aria2# opkg install luci-app-dockerman_v0.4.3_all.ipk
Multiple packages (luci-app-dockerman and luci-app-dockerman) providing same name marked HOLD or PREFER. Using latest.
Upgrading luci-app-dockerman on root from v0.4.0-beta to v0.4.3...
Collected errors:
 * check_data_file_clashes: Package luci-app-dockerman wants to install file /etc/init.d/dockerd
        But that file is already provided by package  * docker-ce
 * opkg_install_cmd: Cannot install package luci-app-dockerman.

**Comment by lisaac** [comment]
重新下载v0.4.3
然后用--force-overwrite安装

**Comment by adaaaaaa** [comment]
设置
Docker Daemon Dockerman 
这两个页面怎么有点奇怪？？第一个是上面有一块空白，第二个是下面有一块空白。。。

**Comment by adaaaaaa** [comment]
@lisaac 
设置
Docker Daemon Dockerman
这两个页面怎么有点奇怪？？第一个是上面有一块空白，第二个是下面有一块空白。。。

**Comment by lisaac** [comment]
@adaaaaaa 
首先是 luci 版本的问题，用新版就不会有这个问题
其次是主题问题，用默认bootscrap主题会好点

**Comment by lisaac** [comment]
@adaaaaaa 
最新提交已修复

**Comment by adaaaaaa** [comment]
你喵的。。。😂😂
