### ISSUE TITLE
500 内部服务器错误

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-app-dockerman#3]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/docker/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:39: Failed to load template 'docker/docker_status'.
Error while parsing template '/usr/lib/lua/luci/view/docker/docker_status.htm':
No such file or directory
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by lisaac** [comment]
目测是你删除了自带的luci-app-docker所致，计划下个版本改一下overview页面

**Comment by tcsr200722** [comment]
能不能把docker镜像安装其他的挂载点？


 
---原始邮件---
发件人: "lisaac"<notifications@github.com&gt;
发送时间: 2019年12月19日 13:20:58
收件人: "lisaac/luci-app-dockerman"<luci-app-dockerman@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tcsr200722"<350524166@qq.com&gt;;
主题: Re: [lisaac/luci-app-dockerman] 500 内部服务器错误 (#3)



目测是你删除了自带的luci-app-docker所致，计划下个版本改一下overview页面

**Comment by lisaac** [comment]
> 能不能把docker镜像安装其他的挂载点？

与插件无关 docker 服务端配置问题，或者把其他目录挂载到默认`DockerRootDir`就可以

**Comment by tcsr200722** [comment]
谢谢大佬

**Comment by lisaac** [comment]
已修改 overview 页面
