### ISSUE TITLE
一些问题,我貌似缺少了什么文件

### ISSUE THREAD

**Issue by fuqiang03** [lisaac/luci-app-dockerman#30]
一些问题,我貌似缺少了什么文件
openwrt master包括luci
如图
![QQ截图20200312222020](https://user-images.githubusercontent.com/26851715/76531313-fcb50e80-64af-11ea-9c56-c0ba87be7061.png)
![QQ截图20200312222030](https://user-images.githubusercontent.com/26851715/76531318-fe7ed200-64af-11ea-93a7-3ea284630afa.png)
![QQ截图20200312222108](https://user-images.githubusercontent.com/26851715/76531322-ff176880-64af-11ea-8b81-10fbe25120bf.png)

**Comment by fuqiang03** [comment]
![QQ截图20200312222326](https://user-images.githubusercontent.com/26851715/76531413-253d0880-64b0-11ea-8505-0af75856d790.png)

**Comment by fuqiang03** [comment]
所有依赖都存在

**Comment by lisaac** [comment]
用默认主题时试试吧

**Comment by lisaac** [comment]
最新版已经修复

**Comment by fuqiang03** [comment]
谢谢 已经好了
