### ISSUE TITLE
051和052都报错了？？

### ISSUE THREAD

**Issue by adaaaaaa** [lisaac/luci-app-dockerman#31]
Tue Mar 17 11:09:26 2020 daemon.err uhttpd[15327]: //usr/lib/opkg/info/luci-app-dockerman.postinst: /etc/uci-defaults/luci-app-dockerman: line 11: /etc/init.d/dockerd: not found
Tue Mar 17 11:09:49 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Tue Mar 17 11:09:49 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Tue Mar 17 11:10:08 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Tue Mar 17 11:10:08 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Tue Mar 17 11:10:09 2020 daemon.err uhttpd[1961]: /etc/rc.common: line 39: /etc/init.d/dockerd: not found
Tue Mar 17 11:11:05 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Tue Mar 17 11:11:05 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Tue Mar 17 11:11:12 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Tue Mar 17 11:11:12 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Tue Mar 17 11:11:21 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Tue Mar 17 11:11:21 2020 daemon.err uhttpd[1961]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Tue Mar 17 11:11:21 2020 daemon.err uhttpd[1961]: /etc/rc.common: line 39: /etc/init.d/dockerd: not found

**Comment by adaaaaaa** [comment]
直接更新之后就这样了。。。

**Comment by lisaac** [comment]
建议重新编译，不支持从lean-mod版本更新
