### ISSUE TITLE
dockerman luci界面显示不完整

### ISSUE THREAD

**Issue by ITdesk01** [lisaac/luci-app-dockerman#33]
使用固件版本 ：OpenWrt R20.3.19 / LuCI Master (git-20.088.29068-cebe120)

使用问题
服务菜单里面的dockerman界面与你们描述的有点出入，是我没有配置好，还是差什么参数吗？？

界面如下：
![image](https://user-images.githubusercontent.com/38835844/78763501-ccca2f80-79b7-11ea-8f32-5e1f27f82699.png)

依赖包如下
![image](https://user-images.githubusercontent.com/38835844/78763551-dce20f00-79b7-11ea-876b-8611b2b2b812.png)

**Comment by lisaac** [comment]
请使用本仓库的代码
