### ISSUE TITLE
出现“not supported as upperdir”报错

### ISSUE THREAD

**Issue by hue715** [lisaac/luci-app-dockerman#34]
出现“not supported as upperdir”报错，不知是不是dockerman问题，以前的版本没出现这个报错。使用Lean大的openwrt（内核版本 ： 4.19.108）。
[   74.352740] overlayfs: filesystem on '/opt/docker/check-overlayfs-support867371572/upper' not supported as upperdir
[   74.420000] overlayfs: filesystem on '/opt/docker/check-overlayfs-support041837059/upper' not supported as upperdir
[   74.757926] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready

**Comment by lisaac** [comment]
明显docker-ce的问题
