### ISSUE TITLE
安装完成后会报错:/usr/share/dockerman/dockerd-config.lua:8:bad argumen...

### ISSUE THREAD

**Issue by christinkaka** [lisaac/luci-app-dockerman#35]
root@OpenWrt:~/tmp# /usr/share/dockerman/dockerd-config.lua:8:bad argument #1 to 'parse' (string expected, got nil)

**Comment by lisaac** [comment]
是个问题
如果有安装docker-ce应该就不会有这个错误

**Comment by lisaac** [comment]
已修复
