### ISSUE TITLE
docker搭建jellyfin转码问题

### ISSUE THREAD

**Issue by ITdesk01** [lisaac/luci-app-dockerman#38]
我用docker搭建了jellyfin，需要用到硬件转码功能

1.首先我的机器是全支持的
`root@OpenWrt:~# ls /dev/dri/
`
`card0       renderD128`

2.dockerman里面设置
![dev](https://user-images.githubusercontent.com/38835844/81311971-a253bb00-90b8-11ea-89bb-7f1c90ca9b00.PNG)

3.奇怪的事情来了，我在jellyfin里面完全没有找到这个显卡驱动
![jellyfin](https://user-images.githubusercontent.com/38835844/81312286-0d04f680-90b9-11ea-81f6-48c5854303b6.PNG)

4.用命令行可以正常看到了
![命令执行](https://user-images.githubusercontent.com/38835844/81313992-2a3ac480-90bb-11ea-8927-f57315d42308.PNG)

我参考的是这个文章https://aisoa.cn/post-2755.html

**Comment by lisaac** [comment]
--decice中内容填错了，可以参照placeholder填写，或者用命令行解析自动填写

**Comment by ITdesk01** [comment]
--decice的内容就是命令行自动解析填写的
我在这个位置输入了我上面的命令，
![捕获](https://user-images.githubusercontent.com/38835844/81460313-256b3300-91d7-11ea-8f2f-073c06363c6a.JPG)

自动解析完成就是显示
![image](https://user-images.githubusercontent.com/38835844/81460335-43389800-91d7-11ea-93e2-8ebb2683292f.png)

你可以试试我的命令
`docker run --name test -d -p 8096:8096 -v /jellyfin/config:/config -v /test/video:/media 
 --device=/dev/dir/renderD12 jellyfin/jellyfin`

保存完成再进行编辑就会发现没有这个参数
![02](https://user-images.githubusercontent.com/38835844/81460446-015c2180-91d8-11ea-92b8-a679930a769e.JPG)



首先我现在已经可以正常使用了，用的是命令行创建的容器，其次就是这个自动解析是否还需要改进一下，我这边没有别的问题了，感谢回复

**Comment by lisaac** [comment]
奇怪了，你确定使用了最新版本的dockerman了吗？

**Comment by ITdesk01** [comment]
> 奇怪了，你确定使用了最新版本的dockerman了吗？

我回去再编译一下吧，我前两天才编译

**Comment by ITdesk01** [comment]
测试了一下，问题依旧
这条命令自动解析，依旧是下面截图

![01](https://user-images.githubusercontent.com/38835844/81478731-ba127700-9251-11ea-9647-6148e9c76d69.PNG)

`docker run -d --name jellyfin  -p 8096:8096 -v /mnt/sdb3/jellyfin/cache:/cache  -v /mnt/sdb3/jellyfin/config:/config -v /mnt/sda1/video:/video --device=/dev/dri/renderD128  jellyfin/jellyfin`


![捕获](https://user-images.githubusercontent.com/38835844/81478679-7881cc00-9251-11ea-9d94-b8c1993b820b.PNG)

**Comment by lisaac** [comment]
已经和之前的内容不一样了噢，你新建的容器中还是没有这个设备吗？

**Comment by lisaac** [comment]
已经和之前的内容不一样了噢，你新建的容器中还是没有这个设备吗？

**Comment by lisaac** [comment]
已经和之前的内容不一样了噢，你新建的容器中还是没有这个设备吗？

**Comment by ITdesk01** [comment]
> 已经和之前的内容不一样了噢，你新建的容器中还是没有这个设备吗？

保存以后再进去看，直接空白了
![捕获](https://user-images.githubusercontent.com/38835844/81519737-cfcc8d00-9374-11ea-9bb5-9cc6451f92d2.JPG)

依旧没有看到
![捕获01](https://user-images.githubusercontent.com/38835844/81520008-9e07f600-9375-11ea-953d-302d58b69d66.JPG)

我觉得还是你的命令行自动解析有问题
。同样的命令
`docker run -d --name jellyfin -p 8096:8096 -v /mnt/sdb3/jellyfin/cache:/cache -v /mnt/sdb3/jellyfin/config:/config -v /mnt/sda1/video:/video --device=/dev/dri/renderD128 jellyfin/jellyfin`


命令行启动  正常
luci解析命令行   失败

**Comment by lisaac** [comment]
感谢，这段时间一直很忙，最新版已修复，请检查一下

**Comment by ITdesk01** [comment]
问题已经解决了，现在上面的命令可以正常用了，感谢，我还提了一个排版建议希望采纳一下
