### ISSUE TITLE
luci界面排版建议

### ISSUE THREAD

**Issue by ITdesk01** [lisaac/luci-app-dockerman#39]
docker的luci原版界面
![image](https://user-images.githubusercontent.com/38835844/81460559-b989ca00-91d8-11ea-9e91-b324f1a7c3de.png)

能否改以下界面，这样方便大家点击
![03](https://user-images.githubusercontent.com/38835844/81460579-d2927b00-91d8-11ea-8023-c4b5eec7fb9c.JPG)

docker其实可以归类到服务里面去，没有必要单独成为菜单，这样子看起来简单点

当然这是个建议，如果您觉得已经很好了，你可以关掉这个issue，感谢

**Comment by lisaac** [comment]
暂时不考虑变更，现在docker入口比较方便
如果有很多用户都这样建议，会考虑更改

**Comment by lloyd18** [comment]
臣附议，目前luci-theme-argon主题虽然适配了图标，但在手机端是不显示的，很别扭。

**Comment by Mrjia1011** [comment]
argon有docker图标，反而现在上网控制没图标

**Comment by 233Bazinga** [comment]
这个 id 标签可以自定义显示吗
![image](https://user-images.githubusercontent.com/52889695/104916463-132fce80-59cd-11eb-9d0b-5fe069c8beac.png)

**Comment by lfm09** [comment]
赞同楼主建议，放到服务里比较好。

另外，在“窗口->信息“界面，由于其中的内容是居中显示，碰到较长内容时会导致其他行的内容看不到，需要左右移动来查看，向右移动时又会遮挡信息、ID等标题，非常不便。建议改为左对齐，或者是对太长的内容自动折行显示。

![Screenshot_2021-04-21 OpenWrt - LuCI](https://user-images.githubusercontent.com/69192865/115497490-57698e00-a29e-11eb-8063-10ef4b4c9af0.png)

**Comment by lxl6125** [comment]
自己改下源码不就行咯，多大点事啊
[https://github.com/lxl6125/openwrt-packages/commit/a8595ea4fda6396832d0f63da250b46fa60d9f8b](url)
)![2021-05-13_20-31](https://user-images.githubusercontent.com/21015800/118126031-4f7ab500-b42a-11eb-9973-d6e0cd3107b5.png)

**Comment by People-11** [comment]
附议

**Comment by lxl6125** [comment]
用我这个试试，只改了入口位置
https://github.com/lxl6125/luci-app-dockerman
