### ISSUE TITLE
v0.1.5  500 内部服务器错误

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-app-dockerman#4]
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/docker/networks'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/simpleform'.
A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/tblsection'.
A runtime error occured: /usr/lib/lua/luci/template.lua:39: Failed to load template 'cbi/xfvalue'.
Error while parsing template '/usr/lib/lua/luci/view/cbi/xfvalue.htm':
No such file or directory
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by lisaac** [comment]
fixed, forgot to upload xfvalue.htm
