### ISSUE TITLE
docker 容器导出与导入

### ISSUE THREAD

**Issue by ITdesk01** [lisaac/luci-app-dockerman#40]
HI
    能否做一个选项。可以让我们导出或者导入我先现在正常使用的容器，下一次万一系统搞坏了，我还可以还原回去，不至于要重新配置容器里的设置

**Comment by lisaac** [comment]
`docker`有`export`功能，容器导出的是`tar`，导入后是容器这个`rootfs`对应的镜像，虽然可以保存配置，但仍然需要创建容器，而且会导致原本镜像信息丢失。

最好的办法是将容器里的配置通过`-v`映射到磁盘持久化，或者备份`docker root dir`

**Comment by ITdesk01** [comment]
那理论上，假设我新建了一个jellyfin容器，将他的配置文件-v映射到硬盘，下次系统崩溃，我只要按路径还原，东西应该都在吧

**Comment by lisaac** [comment]
> 那理论上，假设我新建了一个jellyfin容器，将他的配置文件-v映射到硬盘，下次系统崩溃，我只要按路径还原，东西应该都在吧

理论上是的，实际操作的时候需要注意，是否全部的配置文件都进行了映射

**Comment by ITdesk01** [comment]
好的，感谢你的回复
