### ISSUE TITLE
大体积镜像无法完成解压

### ISSUE THREAD

**Issue by garypang13** [lisaac/luci-app-dockerman#41]
nginx+uwsgi
对于体积超过500M的镜像,每次 extracting 到400多M左右就会出现 502 Bad Gateway 错误
内存和空间容量确定是够的.

**Comment by lisaac** [comment]
#13

**Comment by garypang13** [comment]
我有修改 uwsgi_read_timeout 300s;
没修改之前会提示504 time out,修改之后变成了 502 Bad Gateway
所以应该不止是超时的问题.

**Comment by lisaac** [comment]
是import还是pull的时候？
即使是1G+的镜像都没碰到这个问题

**Comment by garypang13** [comment]
pull的时候,我用的是Nginx而非uhttpd,

**Comment by lisaac** [comment]
不怎么熟悉 uwsgi/nginx
刚刚安装并测试了一下
除了在 `/etc/nginx/conf.d/luci.locations` 中配置 nginx 的超时：
`uwsgi_read_timeout 300;`
还需要在 `/etc/uwsgi/vassals/luci-webui.ini` 中配置 uwsgi 的超时：
`cgi-timeout = 300`

**Comment by garypang13** [comment]
确实加上 cgi-timeout = 300 后正常了, 感谢!

**Comment by tty228** [comment]
# 更改 uhttpd 脚本超时时间，避免如 docker 拉取失败
uci set uhttpd.uhttpd.script_timeout='1800'
uci commit uhttpd
/etc/init.d/uhttpd restart
