### ISSUE TITLE
macvlan 接口报错 DEVICE_CLAIM_FAILED

### ISSUE THREAD

**Issue by garypang13** [lisaac/luci-app-dockerman#43]
openwrt snapshot X86_64 
luci 19.07
![image](https://user-images.githubusercontent.com/48883331/82860458-401a0780-9f4c-11ea-993b-cc6a33dac211.png)

**Comment by lisaac** [comment]
请自行检查内核是否支持 macvlan

**Comment by garypang13** [comment]
谢谢.
