### ISSUE TITLE
大佬，用lean大源码编译树梅派4b固件时选择不上此插件

### ISSUE THREAD

**Issue by guitoushayan** [lisaac/luci-app-dockerman#44]
选择上插件不能选择docker-ce，选择了的docker-ce后luci-app-dockerman整行自动消失，不显示了，只剩下docker-ce和ttyd这两行，不选择docker-ce后luci-app-dockerman自己又出现了，显示完整

**Comment by lisaac** [comment]
应该是缺少docker-ce
参考https://github.com/openwrt/packages/blob/master/utils/docker-ce/

**Comment by guitoushayan** [comment]
make[3]: Entering directory '/home/ty/lede/package/utils/docker-ce'
grep: ../containerd/Makefile: No such file or directory
OK: Expected ../containerd/Makefile source version
'7ad184331fa3e55e52b890ea95e65ba581ae3429', found ''
grep: ../libnetwork/Makefile: No such file or directory
OK: Expected ../libnetwork/Makefile source version
'0941c3f409260d5f05cfa6fc68420d8ad45ee483', found ''
grep: ../runc/Makefile: No such file or directory
OK: Expected ../runc/Makefile source version
'dc9208a3303feef5b3839f4323d9beb36df0a9dd', found ''
grep: ../tini/Makefile: No such file or directory
OK: Expected ../tini/Makefile source version
'fec3683b971d9c3ef73f284f176672c44b448662', found ''
Makefile:36: ../../lang/golang/golang-package.mk: No such file or directory
make[3]: *** No rule to make target '../../lang/golang/golang-package.mk'.
Stop.
make[3]: Leaving directory '/home/ty/lede/package/utils/docker-ce'
time: package/utils/docker-ce/compile#0.08#0.02#0.10
package/Makefile:111: recipe for target 'package/utils/docker-ce/compile'
failed
make[2]: *** [package/utils/docker-ce/compile] Error 2
make[2]: Leaving directory '/home/ty/lede'
package/Makefile:107: recipe for target
'/home/ty/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile'
failed
make[1]: ***
[/home/ty/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile]
Error 2
make[1]: Leaving directory '/home/ty/lede'
/home/ty/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

添加上以后编译显示这个错误，google没找到可参考的案例

lisaac <notifications@github.com> 于2020年6月3日周三 上午7:37写道：

**Comment by lisaac** [comment]
docker-ce 编译相关问题，请自行解决
