### ISSUE TITLE
大佬能不能将源文件的目录结构调整一下

### ISSUE THREAD

**Issue by 9l** [lisaac/luci-app-dockerman#46]
大佬能不能将源文件的目录结构调整一下，将 dockerman 的源文件放到 luci-app-dockerman 的子目录下，这样就能项目直接添加到 openwrt 的 feeds.conf.default 中自动下载安装了

**Comment by lisaac** [comment]
不调整了，可以直接将 makefile 放入源中，编译的时候会自己下载

另外：目前 openwrt 官方已经收录了 luci-app-dockerman 
https://github.com/openwrt/luci/pull/4073

会继续同步更新
