### ISSUE TITLE
自己编译的ipk没有那个加号+

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-app-dockerman#5]
![2019-12-25 22-24-52屏幕截图](https://user-images.githubusercontent.com/28672578/71447083-8f71c700-2765-11ea-95f3-ce6734b28bf1.png)

**Comment by lisaac** [comment]
这其实是 lean‘s luci 的 bug
https://github.com/coolsnowwolf/luci/issues/16
已提交PR:
https://github.com/coolsnowwolf/luci/pull/17

v0.1.7 已经通过添加自定义 simpleform 的方式修复

**Comment by tcsr200722** [comment]
谢谢！


 
---原始邮件---
发件人: "lisaac"<notifications@github.com&gt;
发送时间: 2019年12月26日 12:16:06
收件人: "lisaac/luci-app-dockerman"<luci-app-dockerman@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tcsr200722"<350524166@qq.com&gt;;
主题: Re: [lisaac/luci-app-dockerman] 自己编译的ipk没有那个加号+ (#5)



这其实是 lean‘s luci 的 bug
 coolsnowwolf/luci#16
 已提交PR:
 coolsnowwolf/luci#17
 
v0.1.7 已经通过添加自定义 simpleform 的方式修复
