### ISSUE TITLE
官方luci合并建议

### ISSUE THREAD

**Issue by hue715** [lisaac/luci-app-dockerman#53]
由于官方luci已包含luci-app-dockerman，lisaac大神能否发pull申请，合并本项目的更改？
<img width="706" alt="截屏2020-07-03 下午11 15 44" src="https://user-images.githubusercontent.com/22958922/86481719-21950080-bd83-11ea-8247-914d7c2bef28.png">

**Comment by lisaac** [comment]
官方的使用就是本仓库最新代码

**Comment by hue715** [comment]
> 官方的使用就是本仓库最新代码

我看到这里最新的commit并没有合并到官方包中。
