### ISSUE TITLE
在lean的openwrt make menuconfig的时候出错

### ISSUE THREAD

**Issue by yubanmeiqin9048** [lisaac/luci-app-dockerman#55]
ERROR: please fix package/lean/luci-app-dockerman/applications/luci-app-dockerman/Makefile - see logs/package/lean/luci-app-dockerman/applications/luci-app-dockerman/dump.txt for details

dump.txt：
Makefile:17: ../../luci.mk: No such file or directory
make[2]: *** No rule to make target '../../luci.mk'.  Stop.

**Comment by lisaac** [comment]
忘记push了，已经修改，请测试
