### ISSUE TITLE
更改Docker根目录不生效

### ISSUE THREAD

**Issue by ITdesk01** [lisaac/luci-app-dockerman#58]
我修改了Docker根目录，重启了几次，依旧还是opt，开机的时候系统日志还有报错，请修复，谢谢

###系统状态
![image](https://user-images.githubusercontent.com/38835844/89186747-cf880a80-d5ce-11ea-86ff-1d43978c5fb8.png)

###docke界面
![image](https://user-images.githubusercontent.com/38835844/89186692-bc753a80-d5ce-11ea-8063-06357665dcb8.png)

###系统日志报错
`Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables v1.8.4 (legacy): Couldn't load target `DOCKER':No such file or directory
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman:
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: Try `iptables -h' or 'iptables --help' for more information.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables v1.8.4 (legacy): Couldn't load target `DOCKER':No such file or directory
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman:
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: Try `iptables -h' or 'iptables --help' for more information.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables v1.8.4 (legacy): Couldn't load target `DOCKER-USER':No such file or directory
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman:
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: Try `iptables -h' or 'iptables --help' for more information.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables v1.8.4 (legacy): Couldn't load target `DOCKER-ISOLATION-STAGE-1':No such file or directory
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman:
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: Try `iptables -h' or 'iptables --help' for more information.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables v1.8.4 (legacy): Couldn't load target `DOCKER':No such file or directory
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman:
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: Try `iptables -h' or 'iptables --help' for more information.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: iptables: No chain/target/match by that name.
Mon Aug  3 20:48:52 2020 daemon.notice procd: /etc/rc.d/S99dockerman: Command failed: Not found`

**Comment by li-xunhuan** [comment]
俺也一样

**Comment by zlf179** [comment]
这个问题我解决了
要修改root-dir 得先停用docker  然后进目录etc/config里的dockerman和dockerd两个文件中对应root-dir全改成你需要的目录
然后启用docker  目录就被修改成功了 感觉这个设定有点问题

**Comment by ITdesk01** [comment]
> 这个问题我解决了
> 要修改根目录得先停用docker 然后进目录etc/config里的dockerman和dockerd两个文件中对应data-root全改成你需要的目录
> 然后启用docker 目录就被修改成功了
> 这个BUG太坑了

怪不得修改一个地方没有用

**Comment by zx55666** [comment]
> 这个问题我解决了
> 要修改根目录得先停用docker 然后进目录etc/config里的dockerman和dockerd两个文件中对应data-root全改成你需要的目录
> 然后启用docker 目录就被修改成功了
> 这个BUG太坑了

谢谢老哥，问题解决乐

**Comment by WYC-2020** [comment]
大佬应该是没有加入修改doker-ce配置文件部分，所以导致修改不完全，可以加上了

**Comment by lisaac** [comment]
> 大佬应该是没有加入修改doker-ce配置文件部分，所以导致修改不完全，可以加上了

考虑到目前 openwrt 官方要对 docker 包大改，暂时偷偷懒，先不改了，等稳定了再改
有能力的可以发PR

**Comment by zlf179** [comment]
> > 大佬应该是没有加入修改doker-ce配置文件部分，所以导致修改不完全，可以加上了
> 
> 考虑到目前 openwrt 官方要对 docker 包大改，暂时偷偷懒，先不改了，等稳定了再改
> 有能力的可以发PR

是的 docker要更新20版本新版 而且编译的时候需要的runc也改了  op上游要等主线更新之后才会解决runc版本不匹配的问题 所以等op上游更新完了 再更新这个插件也不迟

**Comment by jeefyang** [comment]
谢谢大佬讲解

**Comment by lisaac** [comment]
刚刚更新了一下，没来得及测试，请各位有条件的测试，谢谢

**Comment by li-xunhuan** [comment]
> 刚刚更新了一下，没来得及测试，请各位有条件的测试，谢谢

```
WARNING: Makefile 'package/lxh/luci-app-dockerman/applications/luci-app-dockerman/Makefile' has a dependency on 'docker', which does not exist
WARNING: Makefile 'package/lxh/luci-app-dockerman/applications/luci-app-dockerman/Makefile' has a dependency on 'dockerd', which does not exist
```
请问这两个依赖从哪儿来啊？用的是`Lede`。盼回复。

**Comment by lisaac** [comment]
> > 刚刚更新了一下，没来得及测试，请各位有条件的测试，谢谢
> 
> ```
> WARNING: Makefile 'package/lxh/luci-app-dockerman/applications/luci-app-dockerman/Makefile' has a dependency on 'docker', which does not exist
> WARNING: Makefile 'package/lxh/luci-app-dockerman/applications/luci-app-dockerman/Makefile' has a dependency on 'dockerd', which does not exist
> ```
> 
> 请问这两个依赖从哪儿来啊？用的是`Lede`。盼回复。

官方已经将 docker-ce 拆分为 dockerd 和 docker 两个包

**Comment by li-xunhuan** [comment]
您这个官方指的是 OpenWrt 官方还是 Lede 啊？

**Comment by lisaac** [comment]
> 您这个官方指的是 OpenWrt 官方还是 Lede 啊？

openwrt 和 lede 已经合并了，就一个官方

**Comment by li-xunhuan** [comment]
emmmmmmm
我用的是这个 Lede：`https://github.com/coolsnowwolf/lede`

**Comment by lisaac** [comment]
> emmmmmmm
> 我用的是这个 Lede：`https://github.com/coolsnowwolf/lede`

你可以自己改 makefile，或者让 lean 升级下 docker

**Comment by li-xunhuan** [comment]
> 你可以自己改 makefile，或者让 lean 升级下 docker

懂了，感谢回复！！
