### ISSUE TITLE
bcm2710架构编译进lean源码后系统日志报错

### ISSUE THREAD

**Issue by bin20088** [lisaac/luci-app-dockerman#61]
Mon Sep 21 00:00:05 2020 daemon.err uhttpd[710]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Mon Sep 21 00:00:05 2020 daemon.err uhttpd[710]: sh: /etc/init.d/dockerman: line 7: config_get: not found
Mon Sep 21 00:00:12 2020 daemon.err uhttpd[710]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Mon Sep 21 00:00:12 2020 daemon.err uhttpd[710]: sh: /etc/init.d/dockerman: line 7: config_get: not found

也启动不了容器。bcm2710架构编译的N1固件

**Comment by lisaac** [comment]
目测是系统某些文件不全，例如/etc/rc.common,  /lib/functions.sh...

**Comment by bin20088** [comment]
> 目测是系统某些文件不全，例如/etc/rc.common, /lib/functions.sh...

大佬能修复吗？你这个简单直观，L大自带的portainer有些复杂。

**Comment by lisaac** [comment]
你自己查一下，相关包有没有少选
这个应该是比较基础的包，所以没有加依赖

**Comment by bin20088** [comment]
> 你自己查一下，相关包有没有少选
> 这个应该是比较基础的包，所以没有加依赖

不好意思大哥，有点小白，都需要哪些依赖啊，实在搞不清

**Comment by bin20088** [comment]
> 你自己查一下，相关包有没有少选
> 这个应该是比较基础的包，所以没有加依赖

大哥方便的话加我QQ83887640帮我i看看行吗？容器刚启动就停止，反反复复

**Comment by bin20088** [comment]
已解决，感谢指导
