### ISSUE TITLE
关于磁盘分区大小与重启OpenWrt之后的若干问题

### ISSUE THREAD

**Issue by yagami1997** [lisaac/luci-app-dockerman#62]
环境：赛扬3965u，8GB内存，基于OpenWrt  5.4.61编译的系统，64MB+512MB结构。最新版的Dockman。成功部署Ubuntu 20.4，使用一切正常，在Ubuntu上部署了完整的Python 3.7开发环境。目前测试DockerMan存在的问题如下“

1. 磁盘分区调整的问题。在刷这个固件之前，我的磁盘已经为OPT准备了22GB的空间，刷完之后正常加载。但我觉得22GB不满意，遂关闭了DockerMan，重新删除22GB的SDA3分区，扩大为37GB，但是挂载之后，Dockerman依然只能使用22GB。无法显示37GB可用，我觉得这是个BUG。

2. 重启OpenWrt之后，Dockerman有一定概率无法自动加载新的OPT分区，而是使用软件包空间，需要手动重新加载SDA3上的OPT分区。这使得容器数据与偶可能丢失。

3. 容器备份的问题。这个问题是我遇到最刚需，也是比较严重的问题。本身3965U运行Ubuntu是没有任何问题的，而且使用也非常顺畅，经过配置的Ubuntu 20.04从69MB扩大到了800MB左右，需要对容器进行备份。目前Dockerman没有提供图形界面的备份工具，但可以用SSH到Openwrt后用Docker Export进行备份。可惜的是，OpenWrt的软件包空间，我这里设定的是512MB，执行这种超出软件包空间的备份，会直接导致软件包空间用完且无法恢复，只能重启。希望增加图形界面的容器与镜像导出功能。OpenWrt的软件包空间一般都很小，希望能把容器和镜像数据直接下载或者转存到SSD的其他分区去。

**Comment by lisaac** [comment]
感谢反馈!
1.显示空间问题，这个问题没碰到过，有空的时候我测试一下。
2.的确有这种几率存在，原因可能是挂载sda3这个操作在docker启动之后，建议的直接将docker root dir 改到 /mnt/sda3
3.关于export功能，我之前也考虑过，不过由于export功能，只是简单的将容器中的rootfs直接导出成一个黑盒镜像。
后续用其进行恢复的时候是恢复成镜像，这就导致与原有容器的镜像布局不符，同时原镜像自带的相关默认参数也会消失。
综上考虑，就没有做容器export。
常规的备份方案应该是将外部存储映射(-v)至容器内部，将需要保存的内容保存至映射目录。这样做，你只需要备份外部的存储目录就可以了。这样，更新容器也很方便。

ps:如果这的有必要，将考虑加入容器export

**Comment by yagami1997** [comment]
好，关于第二点，我稍后再试试，主要是刚配置完Ubuntu，在搞一次太累心，等下次维护的时候我试试看
