### ISSUE TITLE
启动后出现报错,luci进不去了

### ISSUE THREAD

**Issue by SamuelZon258** [lisaac/luci-app-dockerman#64]
/usr/lib/lua/luci/docker.lua:201: attempt to concatenate field 'host' (a nil value)
stack traceback:
	/usr/lib/lua/luci/docker.lua:201: in function 'gen_header'
	/usr/lib/lua/luci/docker.lua:232: in function 'call_docker'
	/usr/lib/lua/luci/docker.lua:289: in function '_ping'
	/usr/lib/lua/luci/model/cbi/dockerman/overview.lua:51: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1340: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1023: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

Openwrt19.07.4

**Comment by lisaac** [comment]
luci源还是本仓库源
重置能解
