### ISSUE TITLE
dockerman不显示 

### ISSUE THREAD

**Issue by 643406834** [lisaac/luci-app-dockerman#65]
用官方Openwrt镜像生成器地址：https://downloads.openwrt.org/snapshots/targets/x86/64/     制作的固件（包含luci-app-dockerman插件），安装在hyper-v虚拟机测试，不显示docker界面
![屏幕截图 2020-12-24 132429](https://user-images.githubusercontent.com/39716940/103063167-6ccdf480-45eb-11eb-9a7e-2e7537488be7.png)
![image](https://user-images.githubusercontent.com/39716940/103063207-8cfdb380-45eb-11eb-878e-f2e918cd4146.png)
![image](https://user-images.githubusercontent.com/39716940/103063221-9850df00-45eb-11eb-97ad-2689b0e81ecb.png)

**Comment by lisaac** [comment]
原因是没有启动 docker daemon

**Comment by 643406834** [comment]
> 原因是没有启动docker daemon

怎样启动，/etc/init.d/目录下找不到docker

**Comment by lisaac** [comment]
@643406834 那就是 docker 问题
