### ISSUE TITLE
求教修改docker0网段的方法

### ISSUE THREAD

**Issue by rxy0424** [lisaac/luci-app-dockerman#66]
由于docker0默认使用了172.17.0.0/16网段，和校园网网段冲突，导致开启docker之后校园网部分服务不能使用。在修改/ect/docker/daemon.json，/etc/config/dockerd和/etc/config/dockerman等文件并重启软路由之后并不能完成修改，求教正确的修改方式。

**Comment by lisaac** [comment]
正常的话 daemon.json，由于 openwrt 中对配置文件修改的特殊性，官方版本目前已经在 /etc/config/ 中给出配置项
