### ISSUE TITLE
求教更改docker源默认服务器的问题

### ISSUE THREAD

**Issue by chibm** [lisaac/luci-app-dockerman#67]
现在luci界面上有2行,分别是默认服务器地址/仓库镜像
我在/etc/config/dockerman和/etc/config/dockerd的配置中,把仓库镜像改了163源,但默认服务器还是https://index.docker.io/v1/怎么改?
现在pull镜像还是很慢,估计用的还是默认服务器.

**Comment by rainbowshine521** [comment]
同问

**Comment by shu0802** [comment]
![1621340253(1)](https://user-images.githubusercontent.com/43750373/118649508-27b69300-b816-11eb-90eb-0c1bf0f53c84.jpg)
这里修改试试

**Comment by lisaac** [comment]
刚刚抽空更新了一下，没有时间测试，请自行测试
