### ISSUE TITLE
L大的源码集成dockerman后偶尔出现一大堆这个日志

### ISSUE THREAD

**Issue by binge8** [lisaac/luci-app-dockerman#68]
L大的源码集成dockerman后偶尔出现一大堆这个日志，3215U。
![微信截图_20210108202222](https://user-images.githubusercontent.com/53508344/104015396-87a98700-51ef-11eb-97ba-e927a7a42203.png)
[系统日志.txt](https://github.com/lisaac/luci-app-dockerman/files/5787149/default.txt)
![微信截图_20210108202515](https://user-images.githubusercontent.com/53508344/104015541-bc1d4300-51ef-11eb-8386-0cba33b267d5.png)
![微信截图_20210108202551](https://user-images.githubusercontent.com/53508344/104015546-bde70680-51ef-11eb-92fe-f25813d86c01.png)

**Comment by lisaac** [comment]
看日志应该是频繁连接 dockerhub 的日志，考虑到你使用了 watchtower，应该是他在查询
