### ISSUE TITLE
在新版本的OP上，仓库镜像 选择了不显示。

### ISSUE THREAD

**Issue by flyhong666** [lisaac/luci-app-dockerman#69]
![2021-01-14_151952](https://user-images.githubusercontent.com/76857714/104557368-1b5dd600-567c-11eb-822e-41574b96c255.png)
![2021-01-14_151929](https://user-images.githubusercontent.com/76857714/104557380-1ef15d00-567c-11eb-917b-32838440a884.png)
希望能修正一下，谢谢了。

**Comment by lisaac** [comment]
刚刚抽空更新了一下，没有时间测试，请测试，谢谢
