### ISSUE TITLE
大佬，容器不能访问外网的原因可能是：

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-app-dockerman#7]
Display detailed information on one or more networks
root@OpenWrt:~# docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "3e9c9abdf84f034ab03bcdcc599f36ef3af6132bb496f06da5ff4cc69d1db7a3",
        "Created": "2020-01-31T23:57:27.823354374Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "345cf973526e4910676a2e71990a4444bcc13e558f7c6b76a14e6ca0ce28112f": {
                "Name": "portainer",
                "EndpointID": "9d3a81910937e9832f44e11a1cdf4fd317d166fc644b3c69a328fc516012e5c7",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "b1b4c6fb1be88b73f28213c58b3b5dd173bf1923e6805290312c4de6e4510481": {
                "Name": "filebrowser",
                "EndpointID": "f012a465bd2f697d33f87b77ef901cfe52c49c787f827b4bed1bc0e632a5d212",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
            "b5322509ee93c2c0989d200455d803d10e6531d135d2c4dc670c43bd33245247": {
                "Name": "BaiduPCS",
                "EndpointID": "c773da151b59fe98097eeb0bdc75dbe4f72d198c6dcc634fdf458f74db1583d2",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            _**"com.docker.network.bridge.enable_ip_masquerade": "false",**_
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }

**Comment by tcsr200722** [comment]
https://blog.csdn.net/btqszl/article/details/80262794

**Comment by tcsr200722** [comment]
"com.docker.network.bridge.enable_ip_masquerade": "false",

**Comment by lisaac** [comment]
还是与插件无关
- bridge 是 docker 自带的
- daemon.json 也是 docker 自带的
