### ISSUE TITLE
Lean的固件集成dockerman后，在拉取镜像并保存时报错

### ISSUE THREAD

**Issue by cocci810123** [lisaac/luci-app-dockerman#74]
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/docker/images'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/dockerman/images.lua:209: attempt to call method 'get' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

您好，请问这个错误是什么问题造成的呢？

**Comment by lisaac** [comment]
请查看置顶 issue
