### ISSUE TITLE
官方可以运行dock

### ISSUE THREAD

**Issue by 643406834** [lisaac/luci-app-dockerman#76]
依赖要添加dockerd， docker显示有BUG，截图如下：
![image](https://user-images.githubusercontent.com/39716940/115560253-fc0fbe00-a2e6-11eb-9514-c3d852abbbe1.png)
![image](https://user-images.githubusercontent.com/39716940/115560371-19dd2300-a2e7-11eb-83d4-083ff453c808.png)

**Comment by lisaac** [comment]
自从 dockerman 合并到 luci 官方源后，他们自行修改的，我没有参与，建议可以用回老版本
