### ISSUE TITLE
在OpenWrt19.07 21.02 docker/overview 無法顯示

### ISSUE THREAD

**Issue by NickSJ08** [lisaac/luci-app-dockerman#77]
我編譯及自行安裝luci-app-dockerman  都無法顯示出現在的畫面 請問有哪邊要修正?
/usr/lib/lua/luci/cbi.lua:53: /usr/lib/lua/luci/model/cbi/dockerman/overview.lua:90: unexpected symbol near '<'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/cbi.lua:53: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1353: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by lisaac** [comment]
自从 dockerman 合并到 luci 官方源后，他们自行修改的，我没有参与，建议可以用回老版本
