### ISSUE TITLE
nginx控制台无法使用...

### ISSUE THREAD

**Issue by blacktitty-y** [lisaac/luci-app-dockerman#78]
是否可以针对nginx做相应修改...

**Comment by lisaac** [comment]
请给出具体信息

**Comment by blacktitty-y** [comment]
点击连接没有反应... 然而自己另外打开页面ip:7682可以打开

**Comment by blacktitty-y** [comment]
> 请给出具体信息

点击连接没有反应... 然而自己另外打开页面ip:7682可以打开

**Comment by lisaac** [comment]
> > 请给出具体信息
> 
> 点击连接没有反应... 然而自己另外打开页面ip:7682可以打开 试过改用回uhttpd没有问题 但是用nginx就是不行

的确没有试过nginx，手头没有nginx的固件，有条件的话发我邮箱做测试

**Comment by blacktitty-y** [comment]
> > > 请给出具体信息
> > 
> > 
> > 点击连接没有反应... 然而自己另外打开页面ip:7682可以打开 试过改用回uhttpd没有问题 但是用nginx就是不行
> 
> 的确没有试过nginx，手头没有nginx的固件，有条件的话发我邮箱做测试

直接发固件吗 请问邮箱多少 需要img还是vmdk?

**Comment by lisaac** [comment]
> > > > 请给出具体信息
> > > 
> > > 
> > > 点击连接没有反应... 然而自己另外打开页面ip:7682可以打开 试过改用回uhttpd没有问题 但是用nginx就是不行
> > 
> > 
> > 的确没有试过nginx，手头没有nginx的固件，有条件的话发我邮箱做测试
> 
> 直接发固件吗 gmail? 需要img还是vmdk?

gmail，img 即可

**Comment by blacktitty-y** [comment]
> > > > > 请给出具体信息
> > > > 
> > > > 
> > > > 点击连接没有反应... 然而自己另外打开页面ip:7682可以打开 试过改用回uhttpd没有问题 但是用nginx就是不行
> > > 
> > > 
> > > 的确没有试过nginx，手头没有nginx的固件，有条件的话发我邮箱做测试
> > 
> > 
> > 直接发固件吗 gmail? 需要img还是vmdk?
> 
> gmail，img 即可

固件已发送 发了http和https两个版本

**Comment by blacktitty-y** [comment]
我配置好了nginx反代替换成默认Luci-app-ttyd端口7681就可以 但是7682就是不行...

**Comment by lisaac** [comment]
今天有空用发给我的镜像试了一下，发现实际上是可以使用的，只是在点击<连接>后加载过程很慢（可能几分钟），最后还是会出来控制台，具体原因不清楚，怀疑与 uwsgi 有关

**Comment by blacktitty-y** [comment]
> 今天有空用发给我的镜像试了一下，发现实际上是可以使用的，只是在点击<连接>后加载过程很慢（可能几分钟），最后还是会出来控制台，具体原因不清楚，怀疑与 uwsgi 有关

奇怪 我是会变成一片空白的页面... 一直卡那里没反应 然而luci-app-ttyd这个终端页面就直接可以显示出来 完全没问题. 那请问这个问题能解决吗?

**Comment by lisaac** [comment]
> > 今天有空用发给我的镜像试了一下，发现实际上是可以使用的，只是在点击<连接>后加载过程很慢（可能几分钟），最后还是会出来控制台，具体原因不清楚，怀疑与 uwsgi 有关
> 
> 奇怪 我是会变成一片空白的页面... 一直卡那里没反应 然而luci-app-ttyd这个终端页面就直接可以显示出来 完全没问题. 那请问这个问题能解决吗?

dockerman 和 ttyd 的区别是：ttyd 是在加载页面的时候就一起加载了，而 dockerman 加载终端页面时动态的，问题就出在动态加载的过程中，目前没有找到具体原因，只能猜测是 uwsgi 的问题。
简单的解决办法就是修改逻辑，让 console 加载的时候就加载终端（目前没考虑这么做），或者直接用 ip:7682

**Comment by blacktitty-y** [comment]
> > > 今天有空用发给我的镜像试了一下，发现实际上是可以使用的，只是在点击<连接>后加载过程很慢（可能几分钟），最后还是会出来控制台，具体原因不清楚，怀疑与 uwsgi 有关
> > 
> > 
> > 奇怪 我是会变成一片空白的页面... 一直卡那里没反应 然而luci-app-ttyd这个终端页面就直接可以显示出来 完全没问题. 那请问这个问题能解决吗?
> 
> dockerman 和 ttyd 的区别是：ttyd 是在加载页面的时候就一起加载了，而 dockerman 加载终端页面时动态的，问题就出在动态加载的过程中，目前没有找到具体原因，只能猜测是 uwsgi 的问题。
> 简单的解决办法就是修改逻辑，让 console 加载的时候就加载终端（目前没考虑这么做），或者直接用 ip:7682

好的 谢谢大佬的解答 我继续折腾下看看
