### ISSUE TITLE
关于 docker-ce 依赖错误问题

### ISSUE THREAD

**Issue by kissyouhunter** [lisaac/luci-app-dockerman#82]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-dockerman:
 *      docker
 *      dockerd
 * opkg_install_cmd: Cannot install package luci-app-dockerman.

没找到在哪选中这两个选项

**Comment by lisaac** [comment]
官方已经将 docker-ce 拆分为 dockerd 和 docker 两个包

**Comment by mingxiaoyu** [comment]
那么lede的 怎么解

**Comment by lisaac** [comment]
自行修改 makefile: 
```
sed -i ':a;N;s|+docker \\\n\t+dockerd|+docker-ce|g;ta' package/luci-app-dockerman/Makefile
```
或者让 lean 更新 docker

**Comment by bleach1991** [comment]
> 自行修改 makefile:
> 
> ```
> sed -i ':a;N;s|+docker \\\n\t+dockerd|+docker-ce|g;ta' package/luci-app-dockerman/Makefile
> ```
> 
> 或者让 lean 更新 docker

这个sed命令无法修改，还是需要手动修改，麻烦修改下这个命令

**Comment by kissyouhunter** [comment]
> > 自行修改 makefile:
> > ```
> > sed -i ':a;N;s|+docker \\\n\t+dockerd|+docker-ce|g;ta' package/luci-app-dockerman/Makefile
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或者让 lean 更新 docker
> 
> 这个sed命令无法修改，执行后文件不变化，还是需要手动修改，麻烦修改下这个命令

我就是手动改的

**Comment by mingxiaoyu** [comment]
if [ -e feeds/packages/utils/docker-ce ];then	
sed -i '/dockerd/d' package/luci-app-dockerman/Makefile	
sed -i 's/+docker/+docker-ce/g' package/luci-app-dockerman/Makefile
fi

我的处理方式。
https://github.com/mingxiaoyu/N1Openwrt/blob/master/diy.sh
