### ISSUE TITLE
打包编译出错

### ISSUE THREAD

**Issue by yeungle** [lisaac/luci-app-dockerman#84]
大神，这两天的源码打包编译老出错，请问咋回事？

**Comment by yeungle** [comment]
![D I9Z4IOMMSB(((6D)2VIAV](https://user-images.githubusercontent.com/75871729/120928538-a026ba80-c717-11eb-9c55-183ae9ae5f9f.png)

**Comment by lisaac** [comment]
https://github.com/lisaac/luci-app-dockerman/issues/82
