### ISSUE TITLE
建议overview概览页setting设置的enable开关勾选□还保留

### ISSUE THREAD

**Issue by gztingting** [lisaac/luci-app-dockerman#87]
### 最新v0.5.17版，首页的开关按钮没有了呢？

*见下图，*:sob:
![没有开关勾选项了？](https://raw.githubusercontent.com/gztingting/luci-theme-argon-dark-mod/master/Screenshot%202021-06-12%20231207-no_enable.jpg)

----------------------------------------------------------------------------------------------------------------------------------------------
:thumbsup:**以前版本，有这个勾选项，很方便随时开与关。**
![有开关勾选项的上一版](https://raw.githubusercontent.com/gztingting/luci-theme-argon-dark-mod/master/Screenshot%202021-06-12%20231125.jpg)

==================================================================================
:whale:**不知道是我的哪里设置问题还是新版本就这么设计的，请教在哪里修改可以把这个开关选型加回来？非常感谢。**

**Comment by lisaac** [comment]
既然有需求，那就下个版本加回来

**Comment by lisaac** [comment]
v0.5.18 已经添加
