### ISSUE TITLE
请教如何在argon_dark_purple主题下增加一个🐳logo

### ISSUE THREAD

**Issue by gztingting** [lisaac/luci-app-dockerman#88]
我选的是某些lua主题，没有显示这个🐳ico，见下图箭头所示位置。
![截图](https://raw.githubusercontent.com/gztingting/luci-theme-argon-dark-mod/master/Screenshot%202021-06-12%20233217.jpg)

----------------------------------------------------------------------
**请问如何修改加上？**

**Comment by lisaac** [comment]
这个需要联系主题作者添加

**Comment by gztingting** [comment]
我可以在哪里修改lua的htm文件增加这个ico？

**Comment by lisaac** [comment]
去年加过一次，不记得了。。抱歉
