### ISSUE TITLE
luci问题

### ISSUE THREAD

**Issue by ksong008** [lisaac/luci-app-dockerman#9]
![123](https://user-images.githubusercontent.com/54489832/74332840-a3cf5900-4dd1-11ea-889c-da033e832b2c.jpg)
在op18.06编译之后，打开概览和储存卷都有luci错误，请问是什么问题

**Comment by lisaac** [comment]
其他页面正常吗？
docker-ce 是按个版本的？

**Comment by ksong008** [comment]
> 其他页面正常吗？
> docker-ce 是哪个版本的？

19.03.5-2
--

**Comment by lisaac** [comment]
> ## 19.03.5-2
> 还有存储卷页面也出错，其他正常

我用的也是这个版本，麻烦请在命令行运行以下命令，并 po 一下：
```
curl -v --unix-socket /var/run/docker.sock http://localhost/volumes
```

**Comment by ksong008** [comment]
> curl -v --unix-socket /var/run/docker.sock http://localhost/volumes

**Comment by lisaac** [comment]
能否把dd镜像或者img发我邮箱，我看一下

**Comment by ksong008** [comment]
> 能否把dd镜像或者img发我邮箱，我看一下
重新编译了一次，界面正常了，不过curl还是48错误，有关系吗？
感谢你的回复

**Comment by lisaac** [comment]
> > 能否把dd镜像或者img发我邮箱，我看一下
> > 重新编译了一次，界面正常了，不过curl还是48错误，有关系吗？
> > 感谢你的回复

没关系的
