### ISSUE TITLE
求教：依赖从 docker-ce 更新到 dockerd

### ISSUE THREAD

**Issue by jzhou404** [lisaac/luci-app-dockerman#91]
我使用snowwolf （https://github.com/coolsnowwolf/lede）最新的代码 编译

发现0.5.17 依赖从 docker-ce 更新到 dockerd，而 snowwolf 还是docker-ce, 请问如何处理？

是否以后就没法用你的的dockerman了？

谢谢

**Comment by lisaac** [comment]
#82
