### ISSUE TITLE
question: lead together luci-app-dockerman from the luci upstream

### ISSUE THREAD

**Issue by feckert** [lisaac/luci-app-dockerman#93]
@lisaac As you know I have integrated [luci-app-dockerman](https://github.com/openwrt/luci/tree/master/applications/luci-app-dockerman) into the luci upstream repository. In the next stable release of openwrt (openwrt-21.02) the application would already be included. Through the integration we have a greater 
reach that users will try out this application. Would it not make sense to have only one code base?

**Comment by lisaac** [comment]
@feckert
Sure, but as you know the code base line was out of sync, it's may takes time to merge it, also there are some commits in luci upstream repository need to rollback.

If so, I will open PR recently.

**Comment by feckert** [comment]
@lisaac that would be create if we could merge the code base again.
For the record:
I have moved the whole uci handling from the dockerman uci file into dockerd uci file.
So in the LuCI we only write the uci into the dockerd uci file. 
So  I have removed the dockerman uci file.

**Comment by lisaac** [comment]
@feckert 
With @hue715's helps, on #97 we've merge the luci update.
We've removed the dockerman uci file as you wish, and also revert some commits, so there are still some conflicts with luci repository.

The question is how we open a PR to commit updates to luci repository? cherry pick or combine into  one commit?
