### ISSUE TITLE
dockerman的根目录上下不一样

### ISSUE THREAD

**Issue by shu0802** [lisaac/luci-app-dockerman#96]
X86固件编译入dockerman的根目录上下不一样。不知是升级docker到最新版的原因，还是固件升级5.10后与dockerman的原因。
（https://github.com/coolsnowwolf/lede）
<img width="1530" alt="微信图片_20210619111056" src="https://user-images.githubusercontent.com/43750373/122630330-4cdc4100-d0f5-11eb-92d0-40137c79ea6a.png">

**Comment by lisaac** [comment]
你是不是保留了原来的设置？
应该应用一次后会同步

如果是，这个问题下个版本修复

**Comment by shu0802** [comment]
> 你是不是保留了原来的设置？
> 应该应用一次后会同步
> 
> 如果是，这个问题下个版本修复

安装上重置后查看就是这样，我再试试。谢谢

**Comment by lisaac** [comment]
> > 你是不是保留了原来的设置？
> > 应该应用一次后会同步
> > 如果是，这个问题下个版本修复
> 
> 安装上重置后查看就是这样，我再试试。谢谢

设置一次应该就会同步，你可以试试

**Comment by shu0802** [comment]
> > > 你是不是保留了原来的设置？
> > > 应该应用一次后会同步
> > > 如果是，这个问题下个版本修复
> > 
> > 
> > 安装上重置后查看就是这样，我再试试。谢谢
> 
> 设置一次应该就会同步，你可以试试

如何设置？能说一下吗，谢谢

**Comment by lisaac** [comment]
现使用最新版dockerman
