### ISSUE TITLE
大佬最新版本的dockerman创建容器后启动提示如下问题

### ISSUE THREAD

**Issue by kissyouhunter** [lisaac/luci-app-dockerman#98]
dockerman用的 0.5.21
luci-lib-docker 0.3.4
版本是 5.10.43
我凌晨自己编译的openwrt和别人的openwrt都出现了这样的问题
在dockerman里创建容器后，点击启动显示如下
![image](https://user-images.githubusercontent.com/63334206/123086255-c3f73980-d455-11eb-97dd-b482d063390d.png)
我试了portainer和adguardhome都这样
用命令创建容器话就一切正常，启动和关闭都没有问题。

**Comment by lisaac** [comment]
请给下命令行

**Comment by kissyouhunter** [comment]
portainer的
docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce
adguardhome的
docker run -d \
    --name adguardhome \
    -v /opt/adguardhome/work:/opt/adguardhome/work \
    -v /opt/adguardhome/conf:/opt/adguardhome/conf \
    -p 5453:53/tcp \
    -p 5453:53/udp \
    -p 4000:3000/tcp \
    adguard/adguardhome

**Comment by lisaac** [comment]
已修复
